### PR TITLE
Fix rock breaker recipe condition

### LINKED ISSUE #3785: Rock breaker recipes don't require any fluids  right now
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

latest

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

dev env

### Expected Behavior

Rock breaker doesn't run without lava / water next to it

### Actual Behavior

Rock breaker does run without lava / water next to it

### Steps to Reproduce

place rock breaker
place creative energy
put in cobblestone

### Additional Information

I think it's caused by going from json -> GTRecipe? 
The json does have it when constructing
Image
but the final recipe doesn't
Image

### PR DESCRIPTION
**Pull request by TarLaboratories**
## What
Fix rock breaker recipe condition

## Implementation Details
Changed `GTRecipeBuilder.toJson` to use `GTRecipeSerializer.CODEC`

## Outcome
Fixes #3785

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/common/recipe/condition/AdjacentFluidCondition.java [hunk 1]
```diff
@@ -138,28 +140,63 @@ public boolean testCondition(@NotNull GTRecipe recipe, @NotNull RecipeLogic reci
...
 
+
     @Override
     public RecipeCondition createTemplate() {
         return new AdjacentFluidCondition();
     }
 
+
+    // Not in use, maybe delete if this ends up not needed
+    private static JsonElement expandShorthand(JsonElement element) {
```
Comment (YoungOnionMC) [inline src/main/java/com/gregtechceu/gtceu/common/recipe/condition/AdjacentFluidCondition.java]: still needed?

**Comment by jurrejelle** [comment]
We should break up the tests into their own files and make them neater since I just put them there for debugging. I can do that when I'm home if u want tho

File: src/main/java/com/gregtechceu/gtceu/common/recipe/condition/AdjacentFluidCondition.java [hunk 2]
```diff
@@ -143,38 +138,26 @@ public RecipeCondition createTemplate() {
...
-        this.fluids = buf.readWithCodec(ops, FLUID_CODEC);
-        return this;
-    }
-
-    @Override
-    public void toNetwork(FriendlyByteBuf buf) {
-        super.toNetwork(buf);
-        var ops = RegistryOps.create(NbtOps.INSTANCE, GTRegistries.builtinRegistry());
-        buf.writeWithCodec(ops, FLUID_CODEC, this.fluids);
+    // Not in use, maybe delete if this ends up not needed
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/common/recipe/condition/AdjacentFluidCondition.java]: This can get deleted :)

File: src/test/java/com/gregtechceu/gtceu/api/recipe/OverclockLogicTest.java [hunk 3]
```diff
@@ -114,6 +134,247 @@ private static BusHolder getBussesAndForm(GameTestHelper helper) {
         return new BusHolder(inputBus1, inputBus2, outputBus1, outputHatch1, controller);
     }
 
+    private static final Codec<HolderSet<Fluid>> FLUID_SET_CODEC = net.minecraft.core.RegistryCodecs
```
Comment (jurrejelle) [inline src/test/java/com/gregtechceu/gtceu/api/recipe/OverclockLogicTest.java]: All tests in this file should be moved, maybe to a seperate codec/serializer test file. The OverclockLogicTest should not end up edited. Sorry, I just threw them somewhere when debugging x3

**Review by jurrejelle — CHANGES_REQUESTED** [review]

File: src/test/java/com/gregtechceu/gtceu/api/recipe/GTRecipeSerializerTest.java [hunk 4]
```diff
@@ -0,0 +1,309 @@
...
+        GTRecipe recipe = GTRecipeSerializer.SERIALIZER.fromJson(GTCEu.id("test"), AFConditionJSON);
+
+        AFConditionJSON.get("config");
+
+        helper.assertTrue(recipe.conditions.stream().anyMatch(x -> x instanceof AdjacentFluidCondition),
+                "Fluid recipe condition did not deserialize properly");
+        helper.succeed();
+    }
+
+    private static final Codec<HolderSet<Fluid>> FLUID_SET_CODEC = net.minecraft.core.RegistryCodecs
```
Comment (jurrejelle) [inline src/test/java/com/gregtechceu/gtceu/api/recipe/GTRecipeSerializerTest.java]: Can you delete the FLUID_SET_CODEC and GPT_tests / GPT_tests_2, they are no longer needed.

File: src/test/java/com/gregtechceu/gtceu/api/recipe/GTRecipeSerializerTest.java [hunk 5]
```diff
@@ -0,0 +1,309 @@
...
+        var ops = RegistryOps.create(JsonOps.INSTANCE, GTRegistries.builtinRegistry());
+
+        // Create a HolderSet with a direct fluid (water)
+        HolderSet<Fluid> directSet = HolderSet.direct(Fluids.WATER.builtInRegistryHolder());
+
+        // Serialize to JSON
+        JsonElement json = FLUID_SET_CODEC.encodeStart(ops, directSet)
+                .getOrThrow(false, System.err::println);
+
+        System.out.println("Serialized direct fluid: " + json);
```
Comment (jurrejelle) [inline src/test/java/com/gregtechceu/gtceu/api/recipe/GTRecipeSerializerTest.java]: Can you remove the system out printlns from all tests

**Review by jurrejelle — CHANGES_REQUESTED** [review]

**Review by jurrejelle — APPROVED** [review]
We definitely need to test this extensively in-game, as this is something that very well could break stuff without us noticing. Apart from that, looks good to me. Really appreciate it, and good fix o7

**Review by YoungOnionMC — CHANGES_REQUESTED** [review]

**Comment by YoungOnionMC** [comment]
Can we also get docs explaining how to construct a new RecipeCondition class(making the class, adding it to our condition registry, example to adding it to a recipe)?

**Review by YoungOnionMC — APPROVED** [review]
