### PR TITLE
Fix quantum tanks' fluid handlers not checking if the contained fluid is valid

### LINKED ISSUE #3714: Exception thrown in Jade showing Quantum Tank
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.1.4

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

My mod <https://github.com/ElytraServers/gtm-quality-of-life>. LMK if you want to have further details.

### Expected Behavior

Not crashing the game.

### Actual Behavior

```
java.lang.IllegalStateException: Can't modify the empty stack.
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.fluids.FluidStack.setAmount(FluidStack.java:175)
	at TRANSFORMER/gtceu@7.1.4/com.gregtechceu.gtceu.api.misc.forge.QuantumFluidHandlerItemStack.getFluid(QuantumFluidHandlerItemStack.java:45)
	at TRANSFORMER/gtceu@7.1.4/com.gregtechceu.gtceu.api.misc.forge.QuantumFluidHandlerItemStack.getFluidInTank(QuantumFluidHandlerItemStack.java:73)
	at TRANSFORMER/gtmqol@99.99.99/cn.elytra.mod.gtmqol.client.item_decorator.FluidHandlerItemDecorator.render(FluidHandlerItemDecorator.java:79)
	at TRANSFORMER/forge@47.1.3/net.minecraftforge.client.ItemDecoratorHandler.render(ItemDecoratorHandler.java:62)
	at TRANSFORMER/jade@11.6.3/snownee.jade.util.ClientProxy.renderItemDecorationsExtra(ClientProxy.java:288)
	at TRANSFORMER/jade@11.6.3/snownee.jade.overlay.DisplayHelper.renderGuiItemDecorations(DisplayHelper.java:95)
	at TRANSFORMER/jade@11.6.3/snownee.jade.overlay.DisplayHelper.drawItem(DisplayHelper.java:208)
	at TRANSFORMER/jade@11.6.3/snownee.jade.impl.ui.ItemStackElement.render(ItemStackElement.java:50)
	at TRANSFORMER/jade@11.6.3/snownee.jade.overlay.TooltipRenderer.draw(TooltipRenderer.java:117)
	at TRANSFORMER/jade@11.6.3/snownee.jade.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:206)
	at TRANSFORMER/jade@11.6.3/snownee.jade.overlay.OverlayRenderer.renderOverlay478757(OverlayRenderer.java:149)
	at TRANSFORMER/jade@11.6.3/snownee.jade.util.ClientProxy.onRenderTick(ClientProxy.java:163)
{Count:1b,id:"gtceu:opv_quantum_tank",tag:{stored:{Amount:0,FluidName:"minecraft:empty"},storedAmount:0L}}
```

I want to render a item decoration to show the inside fluids of the quantum tanks, but it looks like Jade or GTM not handle this condition properly.

### Steps to Reproduce

Just simply place a quantum tank and look at it.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Taskeren**
## What

Fixed a bug where QuantumFluidHandlerItemStack didn't handle empty FluidStacks properly

closes #3714

### CODE REVIEW

**Review by jurrejelle — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/api/misc/forge/QuantumFluidHandlerItemStack.java [hunk 1]
```diff
@@ -42,7 +42,9 @@ protected int getClampedCapacity() {
             return FluidStack.EMPTY;
         }
         FluidStack stack = FluidStack.loadFluidStackFromNBT(tagCompound.getCompound("stored"));
-        stack.setAmount(GTMath.saturatedCast(tagCompound.getLong("storedAmount")));
+        if (stack != FluidStack.EMPTY) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/misc/forge/QuantumFluidHandlerItemStack.java]:
```suggestion
        if (!stack.isEmpty()) {
```

**Review by screret — CHANGES_REQUESTED** [review]

**Review by screret — APPROVED** [review]
