### PR TITLE
lots of tweaks

### LINKED ISSUE #782: Crash with other mods on startup
### GregTech CEu Version

1.1.0

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

Game gets to the title screen.

### Actual Behavior

GT crashes with the error `java.lang.NullPointerException: Cannot invoke "com.gregtechceu.gtceu.api.data.chemical.material.IMaterialRegistryManager.getRegistry(String)" because "com.gregtechceu.gtceu.api.GTCEuAPI.materialManager" is null`

### Steps to Reproduce

Run GT with the mods listed in the logs (though some of these mods are disabled, the crash happens regardless).

### Additional Information

This crash didnt happen with the same set of mods in the previous version of gtceu modern.
I've tried narrowing down what combination of mods causes this error but I'm stumped. It seems to happen only when a combination of mods are there (potentially Steam n Rails + embeddium + balm + at least 1 other but I dont know what they are). The crash only happens about 50% of the time which makes it very hard to test.
`debug.log` and `latest.log`: https://gist.github.com/lonevox/ebfc7e089a9dcd2913ace3bfe4d5409d

### LINKED ISSUE #815: [Bug] Render conflict with REI + Chisel and Bits + GregtechCEu
### GregTech CEu Version

gtceu-1.20.1-1.1.1.a-build_451

### Recipe Viewer Installed

REI

### Environment

Cilent-Side

### Cross-Mod Interaction

Yes

### Expected Behavior

to be able to see the items without crashing when looking at the blocks

### Actual Behavior

When you go to a page that has a lot of gregtech items in it, that is set for chisel and bits time, it will crash only the client.

### Steps to Reproduce

Install build 451
Install rei
Install chisel and bits
do @chisel
go start scrolling, and get a out of bounds array error.

### Additional Information

[crash-2024-01-22_10.29.43-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14011550/crash-2024-01-22_10.29.43-client.txt)
[crash-2024-01-22_10.38.53-client.txt](https://github.com/GregTechCEu/GregTech-Modern/files/14011551/crash-2024-01-22_10.38.53-client.txt)

### PR DESCRIPTION
**Pull request by screret**
- fix item color layers
- remove inverse backround from machine GUIs
- rework default slot layout in machine GUIs
- remove deprecated `GTRegistries#MATERIALS`
- force addon lang generator to be index 0 to allow overriding
- fix all chest loot having NBT tags
- fix drill body texture being tinted
- fix tool heads being generated for materials that don't have them
- add custom durability bars
- register tools in order of tool type instead of material.

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/machine/SimpleTieredMachine.java [hunk 1]
```diff
@@ -394,7 +394,23 @@ protected static EditableUI<SlotWidget, SimpleTieredMachine> createBatterySlot()
             slotWidget.setHandlerSlot(machine.chargerInventory, 0);
             slotWidget.setCanPutItems(true);
             slotWidget.setCanTakeItems(true);
-            slotWidget.setHoverTooltips(LangHandler.getMultiLang("gtceu.gui.charger_slot.tooltip", GTValues.VNF[machine.getTier()], GTValues.VNF[machine.getTier()]).toArray(new MutableComponent[0]));
+            slotWidget.setHoverTooltips(LangHandler.getMultiLang("gtceu.gui.charger_slot.tooltip", GTValues.VNF[machine.getTier()], GTValues.VNF[machine.getTier()]).toArray(Component[]::new));
+        });
+    }
+
+    /**
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/api/machine/SimpleTieredMachine.java:401]: You may want to update that javadoc comment :D

**Review by mikerooni — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/api/machine/SimpleTieredMachine.java (hunk 1 above)
Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/api/machine/SimpleTieredMachine.java:401]: me when I copypaste the code:
