### PR TITLE
Fix ranged item & fluid outputs with minimum 0, and fix SizedIngredient modifying recipe stack sizes in batched recipes.

### LINKED ISSUE #3534: EMI showing bug
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.2

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

Modpack "Sky of Grind"

### Expected Behavior

EMI should just show the base recipe that is registered

### Actual Behavior

It will show what machines in your base done basically

Example:
No machines craft this, it's normal

Image

I place the controller of the machine again and let the recipe run and it will change after that:

Image

Image
If I enable batch mode the value will be changed to the batch mode outcome:

Image

Image

/reload will clear it if there is no machine running on that recipe, will still be bugged if it runs again
It's not only this recipe, mixer and other things as well so not sure where it comes from

### Steps to Reproduce

Mentioned at actual behaviour

### Additional Information

_No response_

### LINKED ISSUE #3593: itemOutputsRanged() with min set to 0 in kubejs makes the ranged output broken
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

v7.0.2

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Architectury `v9.2.14`
EMI `v1.1.22+1.20.1+forge`
GregTech `v7.0.2`
KubeJS `v2001.6.5-build.16`
Rhino `v2001.2.3-build.10`

### Expected Behavior

expected `itemOutputsRanged(item, 0, 2)` to give between 0 and 2 of `item` uniformly, so, for example, to get (on average) 96 iron ingots and 64 gold ingots per 64 of a recipe that outputs from 1-2 iron ingots and 0-2 gold ingots, and to see all the item outputs from the recipe in EMI

### Actual Behavior

the output that has the minimum of 0 sometimes appears and sometimes doesn't after a reload, here's an example of when it doesn't:

Image

when it doesn't appear, it also never drops: 1,536 iron ingots (24 stacks) from 1,024 (16 stacks) of the recipe displayed above.
when it does appear, it drops, but definitely not in a uniform way - from 1,024 tests of this recipe:

Image

got: 1,728 iron ingots + 192 gold ingots (exactly 27 and 3 stacks respectively), which, per 64 items is 108 iron ingots and 12 gold ingots.

### Steps to Reproduce

1. save this script to `kubejs/server_scripts/test.js`:
```js
ServerEvents.recipes(event => {
  event.recipes.gtceu.centrifuge("testing")
    .itemInputs(Item.of("minecraft:cobblestone"))
    .itemOutputsRanged(Item.of("minecraft:iron_ingot"), 1, 2)
    .itemOutputsRanged(Item.of("minecraft:gold_ingot"), 0, 2)
    .duration(1)
    .EUt(1)
})
```
2. `/reload`
3. observe how the gold ingot can randomly disappear from the recipe output list after a certain amount of reloads
4. run the recipe by centrifuging cobblestone

### Additional Information

nothing is broken if the ranged output min is `>0`

### PR DESCRIPTION
**Pull request by DilithiumThoride**
## What
fixes #3593

However, trying to fix this opened a larger can of worms related to how ranged item and fluid outputs pass their results around, and revealed a larger compatibility issue.

As a result, this PR _also_ fixes #3534 

## Implementation Details
Modify NotifiableFluidTank and ItemRecipeCapability to fix both the actual recipe bug and the incorrect XEI display from #3593.
As per embeddedt, Tech22, and screret, modify SizedIngredient, IPI, and IPFI to do deep copies to change stack sizes rather than modifying the arrays returned from getItems() / getStacks(). These changes also fix #3534.
Also fixes Jade display for ranged outputs with a minimum of 0. This bug was hidden by #3593, and fixing it revealed it.

### CODE REVIEW

**Comment by Bolaside** [comment]
😍

File: src/main/java/com/gregtechceu/gtceu/api/capability/recipe/FluidRecipeCapability.java [hunk 1]
```diff
@@ -403,8 +403,8 @@ public void applyWidgetInfo(@NotNull Widget widget,
     // Maps fluids to a FluidEntryList for XEI: either a FluidTagList or a FluidStackList
     public static FluidEntryList mapFluid(FluidIngredient ingredient) {
         int amount;
-        if (ingredient instanceof IntProviderFluidIngredient provider) {
-            amount = provider.getCountProvider().getMaxValue();
+        if (ingredient instanceof IntProviderFluidIngredient) {
+            amount = 1;
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/api/capability/recipe/FluidRecipeCapability.java:407]: Doesn't this strip out actually needed info?

File: src/main/java/com/gregtechceu/gtceu/api/capability/recipe/ItemRecipeCapability.java [hunk 2]
```diff
@@ -498,24 +497,35 @@ private static ItemEntryList mapItem(final Ingredient ingredient) {
...
             if (tagList != null) return tagList;
         }
-        ItemStackList stackList = new ItemStackList();
-        boolean isIntProvider = ingredient instanceof IntProviderIngredient ||
-                (ingredient instanceof SizedIngredient sized && sized.getInner() instanceof IntProviderIngredient);
 
-        UnaryOperator<ItemStack> setCount = stack -> isIntProvider ? stack.copyWithCount(1) : stack;
-        Arrays.stream(ingredient.getItems())
-                .map(setCount)
-                .forEach(stackList::add);
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/api/capability/recipe/ItemRecipeCapability.java:518]: It seems we have completely lost the copyWithCount(1) here? was that on purpose?

File: src/main/java/com/gregtechceu/gtceu/api/machine/trait/NotifiableFluidTank.java [hunk 3]
```diff
@@ -118,31 +118,24 @@ public List<FluidIngredient> handleRecipeInner(IO io, GTRecipe recipe, List<Flui
...
-                    }
-                    amount = fluids[0].getAmount();
                 }
             } else {
                 fluids = ingredient.getStacks();
-                if (fluids.length == 0 || fluids[0].isEmpty()) {
-                    it.remove();
-                    continue;
-                }
-                amount = ingredient.getAmount();
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/api/machine/trait/NotifiableFluidTank.java:144]: When simplifying this action, this case got lost and now instead becomes fluids[0].getAmount() instead of ingredient.getAmount(). Was that on purpose?

File: src/main/java/com/gregtechceu/gtceu/api/capability/recipe/FluidRecipeCapability.java (hunk 1 above)
Comment (YoungOnionMC) [reply src/main/java/com/gregtechceu/gtceu/api/capability/recipe/FluidRecipeCapability.java:407]: we have a custom draw method for displaying the ranged output in EMI, its setting to 1 to not display an amount by default in emi

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/FluidIngredient.java [hunk 4]
```diff
@@ -30,6 +30,7 @@ public class FluidIngredient implements Predicate<FluidStack> {
             .xmap(FluidIngredient::fromJson, FluidIngredient::toJson);
 
     public static final FluidIngredient EMPTY = new FluidIngredient(new Value[0], 0, null);
+    public static final FluidStack[] EMPTYSTACK = new FluidStack[0];
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/FluidIngredient.java]: name this `EMPTY_STACK_ARRAY`

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java [hunk 5]
```diff
@@ -54,8 +54,16 @@ public int getAmount() {
     @Override
     public FluidStack[] getStacks() {
         if (fluidStacks == null) {
-            inner.setAmount(getSampledCount(GTValues.RNG));
-            fluidStacks = inner.getStacks();
+            int cache = getSampledCount(GTValues.RNG);
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java]: name this variable `cachedAmount`

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderIngredient.java [hunk 6]
```diff
@@ -64,9 +65,14 @@ public boolean test(@Nullable ItemStack stack) {
     @Override
     public ItemStack @NotNull [] getItems() {
         if (itemStacks == null) {
-            itemStacks = inner.getItems();
+            int cache = getSampledCount(GTValues.RNG);
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderIngredient.java]: name this variable `cachedCount`

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderIngredient.java [hunk 7]
```diff
@@ -29,6 +29,7 @@
 public class IntProviderIngredient extends Ingredient {
 
     public static final ResourceLocation TYPE = GTCEu.id("int_provider");
+    public static final ItemStack[] EMPTYSTACK = new ItemStack[0];
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderIngredient.java]: name this `EMPTY_STACK_ARRAY`

File: src/main/java/com/gregtechceu/gtceu/integration/top/provider/RecipeOutputProvider.java [hunk 8]
```diff
@@ -58,7 +60,12 @@ protected void addProbeInfo(RecipeLogic recipeLogic, IProbeInfo iProbeInfo, Play
 
                 List<Ingredient> itemOutputs = new ArrayList<>();
                 for (var item : itemContents) {
-                    var stacks = ItemRecipeCapability.CAP.of(item.content).getItems();
+                    ItemStack[] stacks;
+                    if (ItemRecipeCapability.CAP.of(item.content) instanceof IntProviderIngredient provider) {
+                        stacks = provider.getInner().getItems();
+                    } else {
+                        stacks = ItemRecipeCapability.CAP.of(item.content).getItems();
+                    }
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/integration/top/provider/RecipeOutputProvider.java]:
```suggestion
                    Ingredient content = ItemRecipeCapability.CAP.of(item.content);
                    if (content instanceof IntProviderIngredient provider) {
                        stacks = provider.getInner().getItems();
                    } else {
                        stacks = content .getItems();
                    }
```

File: src/main/java/com/gregtechceu/gtceu/integration/top/provider/RecipeOutputProvider.java [hunk 9]
```diff
@@ -75,7 +82,12 @@ protected void addProbeInfo(RecipeLogic recipeLogic, IProbeInfo iProbeInfo, Play
 
                 List<FluidIngredient> fluidOutputs = new ArrayList<>();
                 for (var fluid : fluidContents) {
-                    var stacks = FluidRecipeCapability.CAP.of(fluid.content).getStacks();
+                    FluidStack[] stacks;
+                    if (FluidRecipeCapability.CAP.of(fluid.content) instanceof IntProviderFluidIngredient provider) {
+                        stacks = provider.getInner().getStacks();
+                    } else {
+                        stacks = FluidRecipeCapability.CAP.of(fluid.content).getStacks();
+                    }
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/integration/top/provider/RecipeOutputProvider.java]:
```suggestion
                    FluidIngredient content = FluidRecipeCapability.CAP.of(fluid.content);
                    if (content instanceof IntProviderFluidIngredient provider) {
                        stacks = provider.getInner().getStacks();
                    } else {
                        stacks = content.getStacks();
                    }
```

**Review by screret — DISMISSED** [review]

**Review by jurrejelle — APPROVED** [review]
