### PR TITLE
Fix dupes of Carbon dust and Coal dust

### LINKED ISSUE #3742: Coal Dust, Carbon Dust dupes
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.1.4

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

N/A - only EMI and GregTech Modern.

### Expected Behavior

Expected Gunpowder dust to centrifuge to Saltpeter, Sulfur, and Carbon dust.

### Actual Behavior

Currently, Gunpowder centrifuges to Saltpeter, Sulfur, and Coal dust. (Not carbon!)

However, Gunpowder can be made by mixing Coal, Charcoal, or Carbon dusts. This means that gunpowder can be mixed with Carbon Dust or Charcoal dust and subsequently centrifuged to alchemically convert arbitrary quantities of those Charcoal and Carbon Dust to Coal dust at the cost of EU. 

This is not too bad, but the real issue is that this same recipe allows for the duplication of Carbon and Coal dust.
Since Coal dust can be centrifuged to Carbon dust in a 1:2 ratio, a player could centrifuge Gunpowder to get 3 Coal Dust, centrifuge the 3 Coal Dust into 6 Carbon Dust, and then mix more Gunpowder with only 3 Carbon Dust, netting 3 Carbon dust every loop. Using the above conversion exploit, this Carbon Dust dupe also extends to Coal dust, allowing players to dupe both Coal Dust and Carbon Dust only at the cost of some EU.

### Steps to Reproduce

Make a new world, and look in EMI to see the recipes discusssed above.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zetrock1**
## What
Fix dupes of carbon dust and coal dust
Resolve #3742 

## Implementation Details
Now 2 Saltpeter dust + Sulfur dust + 6 Carbon dust -> gunpowder instead of 2 Saltpeter dust + Sulfur dust + 3 Carbon dust

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/data/recipe/serialized/chemistry/MixerRecipes.java [hunk 1]
```diff
@@ -268,7 +268,7 @@ public static void init(Consumer<FinishedRecipe> provider) {
         MIXER_RECIPES.recipeBuilder("gunpowder_from_carbon").duration(400).EUt(VA[ULV])
                 .inputItems(dust, Saltpeter, 2)
                 .inputItems(dust, Sulfur)
-                .inputItems(dust, Carbon, 3)
+                .inputItems(dust, Carbon, 6)
```
Comment (YoungOnionMC) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/serialized/chemistry/MixerRecipes.java]: This PR should instead turn the centrifuge outputs for gunpowder into 3 carbon instead of 3 coal

**Review by YoungOnionMC — DISMISSED** [review]

**Review by jurrejelle — APPROVED** [review]
