### PR TITLE
Assorted fixes

### LINKED ISSUE #1646: Step assist is active even after unequipping quarktech/nanomuscle boots
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

none

### Expected Behavior

Step assist not working when unequipping quarktech or nanomuscle boots.

### Actual Behavior

Step assist works even when unequipping quarktech or nanomuscle boots until you quit the world you are currently playing

### Steps to Reproduce

1) Equip charged quarktech or nanomuscle boots
2) Unequip them

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by krossgg**
## What
- Added new lang for rotor obstruction tooltip in turbine UIs, previously it used the muffler hatch obstruction message
- Fixed the step-assist behavior

## Implementation Details
Unfortunately this is only possible with an EventHandler via the Forge Event Bus, as I can't find another way to check if the boots has been taken off in order to reset the step-assist. 
To achieve this in a more robust manner, I added a new tag, gtceu:step_boots, which is used in the check. This allows for addon devs to add their own step-assist boots.

## Outcome
Fixes #1646

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/item/armor/ArmorLogicSuite.java [hunk 1]
```diff
@@ -43,11 +47,26 @@ protected ArmorLogicSuite(int energyPerUse, long maxCapacity, int tier, ArmorIte
...
         this.tier = tier;
         this.type = type;
+        MinecraftForge.EVENT_BUS.register(this);
     }
 
     @Override
     public abstract void onArmorTick(Level Level, Player player, ItemStack itemStack);
 
+    // Check if player is wearing step-assist boots and give them extra step height
+    // Could potentially be put in ClientProxy
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/item/armor/ArmorLogicSuite.java]: put it in ForgeCommonEventListener.

**Review by screret — CHANGES_REQUESTED** [review]

**Comment by krossgg** [comment]
oops sorry I requested it from you directly screret

File: src/main/java/com/gregtechceu/gtceu/api/item/armor/ArmorLogicSuite.java [hunk 2]
```diff
@@ -43,6 +44,7 @@ protected ArmorLogicSuite(int energyPerUse, long maxCapacity, int tier, ArmorIte
         this.maxCapacity = maxCapacity;
         this.tier = tier;
         this.type = type;
+        MinecraftForge.EVENT_BUS.register(this);
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/item/armor/ArmorLogicSuite.java]: Remove, this is not a fast operation to do for no reason

**Review by screret — CHANGES_REQUESTED** [review]

**Comment by krossgg** [comment]
Could you rerun the checks? I think gh decided I wasn't worth its time D:

**Comment by YoungOnionMC** [comment]
got you fam

**Review by screret — APPROVED** [review]
