### PR TITLE
1.20 Xaero's series fix

### LINKED ISSUE #4445: Failed to apply mixins when Xaero's World Map 1.40.x is installed
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.4.1 (1.20.1 Forge) / 7.0.2 (1.21.1 NeoForge)

### Minecraft Version

1.20.1 Forge and 1.21.1 NeoForge

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Xaero's World Map (1.40.x)

### Expected Behavior

The Xaero's World Map integration is working.

### Actual Behavior

For Xaero's World Map 1.40.2 and 1.40.4, the Xaero's World Map integration is not working.
For Xaero's World Map 1.40.6, the game crashed.

### Steps to Reproduce

1. Install latest GTCEu and Xaero's World Map 1.40.2/1.40.4
2. Launch the game
3. Join a world
4. Open the world map, finding the buttons to show veins are not appeared

or

1. Install latest GTCEu and Xaero's World Map 1.40.6
2. Launch the game
3. The game crashed

### Additional Information

Xaero's World Map removed some classes, such as `xaero.map.gui.CursorBox`, since 1.40.0.

Log output when Xaero's World Map 1.40.2/1.40.4 is installed:
```
[main/WARN] [mixin/]: Error loading class: xaero/map/gui/ScreenBase (java.lang.ClassNotFoundException: xaero.map.gui.ScreenBase)
[main/ERROR] [mixin/]: gtceu.mixins.json:xaeroworldmap.GuiMapMixin from mod gtceu: Super class 'xaero.map.gui.ScreenBase' of xaeroworldmap.GuiMapMixin was not found in the hierarchy of target class 'xaero/map/gui/GuiMap'
```
Log output when Xaero's World Map 1.40.6 is installed:
```
[Worker-Main-15/INFO] [xaero.map.WorldMap/]: Loading Xaero's World Map - Stage 1/2
[Worker-Main-15/WARN] [mixin/]: Error loading class: xaero/map/gui/CursorBox (java.lang.ClassNotFoundException: xaero.map.gui.CursorBox)
[Worker-Main-15/ERROR] [net.neoforged.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: An unexpected critical error was encountered
```

### LINKED ISSUE #4670: 与xaero的世界地图冲突
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.5.2

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Image
Image

### Expected Behavior

无法启动游戏

### Actual Behavior

加载模组过程中报错

### Steps to Reproduce

同时加载xaero的世界地图和gtceu并启动游戏

### Additional Information

atm9整合包

### PR DESCRIPTION
**Pull request by Taskeren**
## What

Fix crashing when working with the latest Xaeros' mods.

See Also #4642 

## Implementation Details

1. Replaced CurseMaven dependencies of Xaero's to their Maven repo.
2. `CursorBox` -> `Tooltip`.
3. Configuration migration

## Outcome

Fix #4670
Fix #4445

## How Was This Tested

Tested with Xaero's WorldMap and Minimap.

## Potential Compatibility Issues

Will break the compatibility with older Xaeros' mods.

### CODE REVIEW

**Review by YoungOnionMC — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/integration/map/xaeros/minimap/ore/OreVeinElementRenderProvider.java [hunk 1]
```diff
@@ -20,7 +21,8 @@ public OreVeinElementRenderProvider() {}
 
     @Override
     public void begin(MinimapElementRenderLocation location, OreVeinElementContext context) {
-        if (WorldMap.settings.waypoints) {
+        if (WorldMap.INSTANCE.getConfigs().getClientConfigManager().getEffective(
+                WorldMapProfiledConfigOptions.WAYPOINT_BACKGROUNDS)) {
```
Comment (MuuuShin) [inline src/main/java/com/gregtechceu/gtceu/integration/map/xaeros/minimap/ore/OreVeinElementRenderProvider.java:25]: sorry, I wonder why this Variable use `WAYPOINT_BACKGROUNDS` rather than `WAYPOINTS`
