### PR TITLE
Replace no key "....."  in Map

### LINKED ISSUE #4325: [1.21.1] Replace "No key duration in MapLike..." with clearer error message
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

reab/1.21-with-love

### Minecraft Version

1.21.1 NeoForge

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

dev env

### Expected Behavior

When making a recipe that errors for any reason, it should clearly say that the recipe is invalid

### Actual Behavior

```
[14:51:20] [ERROR] ! server_scripts:example.js#13: Error parsing recipe gtceu:assembler/test1 (details below this line): com.google.gson.JsonParseException: No key duration in MapLike[{"type":"gtceu:assembler","_kubejs_changed_marker":{"source":"server_scripts:example.js","line":13}}]
[14:51:20] [ERROR] ! com.google.gson.JsonParseException: No key duration in MapLike[{"type":"gtceu:assembler","_kubejs_changed_marker":{"source":"server_scripts:example.js","line":13}}]
```

### Steps to Reproduce

```
ServerEvents.recipes(event => {
    event.recipes.gtceu.assembler("test1")
        .itemInputs('2x gtceu:iron_geaaaar', 'gtceu:iron_plate')
        .itemOutputs('8x minecraft:dirt')
        .circuit(11)
        .duration(50)
        .EUt(8);
})
```

### Additional Information

It does also say above "[14:51:20] [ERROR] ! server_scripts:example.js#13: Error in 'ServerEvents.recipes': Failed to read ingredient from 2x gtceu:iron_geaaaar: Item with ID gtceu:iron_geaaaar does not exist!" so it's not the highest prio, just thought it'd be something neat to make logging more verbose

### PR DESCRIPTION
**Pull request by zetrock1**
## What
replace no key "......" ->  Recipe "....."  field is invalid
Resolve #4325

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/recipe/GTRecipeSerializer.java [hunk 1]
```diff
@@ -279,13 +280,35 @@ private static MapCodec<GTRecipe> makeCodec(boolean isKubeLoaded) {
...
                     CompoundTag.CODEC.optionalFieldOf("data", new CompoundTag()).forGetter(val -> val.data),
-                    ExtraCodecs.NON_NEGATIVE_INT.fieldOf("duration").forGetter(val -> val.duration),
+                    quietExceptionCodec(ExtraCodecs.NON_NEGATIVE_INT,"duration",isKubeLoaded).forGetter(val -> val.duration),
                     GTRegistries.RECIPE_CATEGORIES.byNameCodec().optionalFieldOf("category", GTRecipeCategory.DEFAULT).forGetter(val -> val.recipeCategory)
             ).apply(instance, GTRecipe::new));
         }
         // spotless:on
     }
 
+    private static <T> MapCodec<T> quietExceptionCodec(Codec<T> codec, String field, boolean isKubeLoaded) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/GTRecipeSerializer.java]: Please this method to `GTCodecUtils`

**Review by TarLaboratories — APPROVED** [review]
