### PR TITLE
Fixed plunger not working

### LINKED ISSUE #954: open a machine, input hatch or a output hatch with plunger will let it drop 1 durability
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.1.3.b

### Recipe Viewer Installed

JEI

### Environment

singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

sky greg(mod pack)

### Expected Behavior

clear current fluid in machine/hatch or just open the gui without dropping 1 durability

### Actual Behavior

it drop 1 durability and opened the gui

### Steps to Reproduce

open the machine/hatch/super tank with any plunger

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by minecraft7771**
## What
Makes the plunger remove fluids from machines while consuming one durability.

## Implementation Details
A small API was added to prevent the plunger from opening the UI, when used on a machine while sneaking.

## Outcome
Fixes https://github.com/gregtechceu/gregTech-modern/issues/954

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/block/MetaMachineBlock.java [hunk 1]
```diff
@@ -269,14 +274,18 @@ public InteractionResult use(BlockState state, Level world, BlockPos pos, Player
             return itemStack.getItem().use(world, player, hand).getResult();
         }
 
+        if (itemStack.getItem() instanceof GTToolItem gtToolItem) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/block/MetaMachineBlock.java]: should check for IGTTool here.

File: src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/PlungerBehavior.java [hunk 2]
```diff
@@ -32,22 +34,36 @@ protected static PlungerBehavior create() {
...
 
-        IFluidTransfer handlerToRemoveFrom = fluidHandler;
-//                player.isCrouching() ?
-//                (fluidHandler instanceof IOFluidTransferList ? ((IOFluidTransferList) fluidHandler).input : null) :
-//                (fluidHandler instanceof IOFluidTransferList ? ((IOFluidTransferList) fluidHandler).output : fluidHandler);
+        IFluidTransfer fluidHandler;
 
-        if (handlerToRemoveFrom != null && handlerToRemoveFrom.drain(FluidHelper.getBucket(), true) != null) {
-            ToolHelper.onActionDone(context.getPlayer(), context.getLevel(), context.getHand());
+        if (context.getLevel().getBlockEntity(context.getClickedPos()) instanceof MetaMachineBlockEntity metaMachineBlockEntity) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/PlungerBehavior.java]: check for IMachineBlockEntity, as some machines (create) use specialized BEs.

**Review by screret — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/PlungerBehavior.java [hunk 3]
```diff
@@ -32,22 +35,36 @@ protected static PlungerBehavior create() {
...
+    public boolean shouldOpenUIAfterUse(UseOnContext context) {
+        return !(context.getPlayer() != null && context.getPlayer().isCrouching());
+    }
+
     @Override
     public InteractionResult onItemUseFirst(ItemStack stack, UseOnContext context) {
-        IFluidTransfer fluidHandler = FluidTransferHelper.getFluidTransfer(context.getLevel(), context.getClickedPos(), context.getClickedFace());
-        if (fluidHandler == null) {
+
+        if (context.getPlayer() == null || !context.getPlayer().isCrouching()) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/PlungerBehavior.java]: use `isShiftDown()` so it works while flying.

**Review by screret — CHANGES_REQUESTED** [review]

**Review by screret — APPROVED** [review]
