### PR TITLE
Fix rotor holder renderer

### LINKED ISSUE #2909: there is no display texture when large turbine rotor rotates
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.6.3

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

monifactory,GregTech CEu Modern Community Pack

### Expected Behavior

Image

### Actual Behavior

Image
attention that there is no rotor display

### Steps to Reproduce

set up the large turbine engine

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by omergunr100**
## What
The renderer relied on the holders content which wasn't synced, so when unloading and reloading the renderer would break.

## Implementation Details
Instead of syncing the inventory I chose to sync the material because that's the only relevant part to the renderer from the item.
In addition re-rendering every time the speed changed wasn't necessary, the only changes that matter we're if speed was 0 and now it's greater than 0 and vice versa, so I implemented the setter explicitly and now it re-renders only if necessary.

## Outcome
Fixes #2909 

## Additional Information
_This section is for screenshots to demonstrate any GUI or rendering changes, or any other additional information that reviewers should be aware of._

## Potential Compatibility Issues
Removed the color member.
Added the `getRotorMaterial` method to `IRotorHolderMachine`.

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IRotorHolderMachine.java [hunk 1]
```diff
@@ -32,6 +33,8 @@ static int getBaseEfficiency() {
         return 100;
     }
 
+    Material getRotorMaterial();
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IRotorHolderMachine.java:39]: this is a compat issue you didn't mention but *who cares?*

File: src/main/java/com/gregtechceu/gtceu/client/renderer/machine/RotorHolderMachineRenderer.java [hunk 2]
```diff
@@ -59,11 +58,10 @@ public void renderMachine(List<BakedQuad> quads, MachineDefinition definition, @
...
                             modelState, -101, 0, true, false));
-                    var rotorBehaviour = TurbineRotorBehaviour.getBehaviour(rotorHolderMachine.getRotorStack());
-                    if (rotorBehaviour != null) {
-                        Material mat = rotorBehaviour.getPartMaterial(rotorHolderMachine.getRotorStack());
-                        boolean emissive = mat.hasProperty(PropertyKey.ORE) &&
-                                mat.getProperty(PropertyKey.ORE).isEmissive();
+                    var material = rotorHolderMachine.getRotorMaterial();
+                    if (material != null && material != GTMaterials.NULL) {
+                        boolean emissive = material.hasProperty(PropertyKey.ORE) &&
+                                material.getProperty(PropertyKey.ORE).isEmissive();
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/client/renderer/machine/RotorHolderMachineRenderer.java:63]: As a note for the future:
emissive should be a material flag outside of the ore property.
why the hell can a material only be emissive if it has an ore that is emissive??

File: src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/part/RotorHolderPartMachine.java [hunk 3]
```diff
@@ -160,6 +156,13 @@ private void updateRotorSpeed() {
         updateRotorSubscription();
     }
 
+    public void setRotorSpeed(int rotorSpeed) {
+        if ((this.rotorSpeed > 0 && rotorSpeed <= 0) || (this.rotorSpeed <= 0 && rotorSpeed > 0)) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/part/RotorHolderPartMachine.java:171]: can rotor speed ever be negative? if not, you could get by with `this.speed == 0 && newSpeed != 0`, no?

File: src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IRotorHolderMachine.java (hunk 1 above)
Comment (omergunr100) [reply src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IRotorHolderMachine.java:39]: > this is a compat issue you didn't mention but _who cares?_

Fair, I guess since it was assumed that the rotor has a material associated with it (for the renderer) I just went "this is fine".
I'll add it to the list.

File: src/main/java/com/gregtechceu/gtceu/client/renderer/machine/RotorHolderMachineRenderer.java (hunk 2 above)
Comment (omergunr100) [reply src/main/java/com/gregtechceu/gtceu/client/renderer/machine/RotorHolderMachineRenderer.java:63]: Yeah, I agree, it's kind of a weird choice, @YoungOnionMC do you want do it in the material system refactor?

File: src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/part/RotorHolderPartMachine.java (hunk 3 above)
Comment (omergunr100) [reply src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/part/RotorHolderPartMachine.java:171]: No, but it shouldn't matter in this case, so I think leaving it this way is fine since it could technically be negative.

**Review by krossgg — APPROVED** [review]

**Review by YoungOnionMC — APPROVED** [review]
