### PR TITLE
Fixed Shaped Recipes for Warning Signs

### LINKED ISSUE #3863: warning_sign_bio_hazard crafting recipe creates a warning_sign_magic_hazard
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [ ] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.6.4

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

JEI

### Environment

Multiplayer - Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

Star Technology

### Expected Behavior

When attempting to craft the bio-hazard block:

Image

### Actual Behavior

I get the magic hazard block:

Image

The bio-hazard block appears uncraftable.

### Steps to Reproduce

Try to craft the bio-hazard block

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Atmudia**
## What
This PR fixes mirrored recipes for hazard recipes which was doing conflict and adding  strict shaped recipe overload with setMaterialInfoData

## Implementation Details
This PR changes these mirrored recipes into strict hazard recipes, added overload for addStrictShapedRecipe

## Outcome
Fixes: #3863

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/data/recipe/misc/MetaTileEntityLoader.java [hunk 1]
```diff
@@ -269,13 +269,13 @@ public static void init(Consumer<FinishedRecipe> provider) {
...
                 GTBlocks.CAUSALITY_HAZARD_SIGN_BLOCK.asStack(), "   ", "YM ", "B  ", 'M',
                 GTBlocks.CASING_STEEL_SOLID.asStack(), 'Y', Tags.Items.DYES_YELLOW, 'B', Tags.Items.DYES_BLACK);
-        VanillaRecipeHelper.addShapedRecipe(provider, true, "warning_turret_hazard",
+        VanillaRecipeHelper.addStrictShapedRecipe(provider, "warning_sign_turret_hazard",
                 GTBlocks.TURRET_HAZARD_SIGN_BLOCK.asStack(), "   ", " MY", "  B", 'M',
                 GTBlocks.CASING_STEEL_SOLID.asStack(), 'Y', Tags.Items.DYES_YELLOW, 'B', Tags.Items.DYES_BLACK);
-        VanillaRecipeHelper.addShapedRecipe(provider, true, "warning_high_pressure_hazard",
+        VanillaRecipeHelper.addStrictShapedRecipe(provider, "warning_sign_high_pressure_hazard",
                 GTBlocks.HIGH_PRESSURE_HAZARD_SIGN_BLOCK.asStack(), "   ", " MY", " B ", 'M',
                 GTBlocks.CASING_STEEL_SOLID.asStack(), 'Y', Tags.Items.DYES_YELLOW, 'B', Tags.Items.DYES_BLACK);
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/misc/MetaTileEntityLoader.java]: Were these additions of "sign" intentional?

**Review by jurrejelle — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/data/recipe/misc/MetaTileEntityLoader.java (hunk 1 above)
Comment (Atmudia) [reply src/main/java/com/gregtechceu/gtceu/data/recipe/misc/MetaTileEntityLoader.java]: yes, I have also updated the other methods to match

**Comment by jurrejelle** [comment]
Closes #3863

**Review by jurrejelle — APPROVED** [review]
