### PR TITLE
ITEM PIPES

### LINKED ISSUE #442: Nbt data lost in irregular interval
### GregTech CEu Version

1.0.12g

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Expected Behavior

Machines keep their inventories

### Actual Behavior

On some points the game failes to load nbt date ( read from log output ) 
I suspect this might be related  to migration from version to version.

Machine inventory are voided, sometimes goes hand in hand with a chrash. but im not shure if these are that much related...

### Steps to Reproduce

1. Start singleplayer world (first time created with ~1.0.10??)
2. game chrashed a few times
3. upgrade gregtech and other mods (sodium, indium, fabric api... no content mods available)
4. since 1.0.12g bug appears
5. moving 12k thought nether to new place
6. bug appears

### Additional Information

recent stacktraces and chrashes:

```
[09:33:44] [Render thread/INFO]: Stopping worker threads
[09:33:44] [Render thread/INFO]: Started 10 worker threads
[09:33:44] [Render thread/INFO]: Stopping worker threads
[09:33:44] [Render thread/INFO]: Started 10 worker threads
[09:33:44] [Render thread/INFO]: Stopping worker threads
[09:33:44] [Render thread/INFO]: Started 10 worker threads
[09:33:45] [Server thread/ERROR]: Failed to load data for block entity gtceu:coke_oven
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:618) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.ingredient.FluidIngredient.fromNetwork(FluidIngredient.java:148) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:30) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:17) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.IContentSerializer.fromNetworkContent(IContentSerializer.java:43) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:231) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.entryReader(GTRecipeSerializer.java:86) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.fromNetwork(GTRecipeSerializer.java:120) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:36) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:18) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.CustomObjectAccessor.writeManagedField(CustomObjectAccessor.java:62) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ManagedAccessor.writeField(ManagedAccessor.java:52) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writeToReadonlyField(IManagedAccessor.java:120) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ReadonlyAccessor.writeField(ReadonlyAccessor.java:85) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.blockentity.IAutoPersistBlockEntity.loadManagedPersistentData(IAutoPersistBlockEntity.java:35) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at net.minecraft.class_2586.handler$bed000$ldlib$injectLoad(class_2586.java:1544) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_11014(class_2586.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_17897(class_2586.java:132) ~[client-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_2586.method_11005(class_2586.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_39797(class_2852.java:408) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:751) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:739) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Invalid tag id: -128
	at net.minecraft.class_4614$1.method_39878(class_4614.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23264(class_4614.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23262(class_4614.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[client-intermediary.jar:?]
	... 50 more
[09:33:45] [Server thread/WARN]: Skipping BlockEntity with id gtceu:coke_oven
[09:35:24] [Render thread/INFO]: [System] [CHAT] [Debug]: Key bindings:
``` 

```

[07:48:35] [Render thread/INFO]: Started 10 worker threads
[07:48:35] [Server thread/ERROR]: Failed to load data for block entity gtceu:lv_steam_turbine
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:618) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.ingredient.FluidIngredient.fromNetwork(FluidIngredient.java:148) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:30) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:17) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.IContentSerializer.fromNetworkContent(IContentSerializer.java:43) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:231) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.entryReader(GTRecipeSerializer.java:86) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.fromNetwork(GTRecipeSerializer.java:118) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:36) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:18) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.CustomObjectAccessor.writeManagedField(CustomObjectAccessor.java:62) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ManagedAccessor.writeField(ManagedAccessor.java:52) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writeToReadonlyField(IManagedAccessor.java:120) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ReadonlyAccessor.writeField(ReadonlyAccessor.java:85) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.blockentity.IAutoPersistBlockEntity.loadManagedPersistentData(IAutoPersistBlockEntity.java:35) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at net.minecraft.class_2586.handler$bed000$ldlib$injectLoad(class_2586.java:1544) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_11014(class_2586.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_17897(class_2586.java:132) ~[client-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_2586.method_11005(class_2586.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_39797(class_2852.java:408) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:751) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:739) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Invalid tag id: -128
	at net.minecraft.class_4614$1.method_39878(class_4614.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23264(class_4614.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23262(class_4614.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[client-intermediary.jar:?]
	... 50 more
[07:48:35] [Server thread/WARN]: Skipping BlockEntity with id gtceu:lv_steam_turbine
[07:48:35] [Server thread/ERROR]: Failed to load data for block entity gtceu:lv_chemical_reactor
net.minecraft.class_148: Loading NBT data
	at net.minecraft.class_2507.method_10626(class_2507.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_30616(class_2540.java:636) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_10798(class_2540.java:618) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.ingredient.FluidIngredient.fromNetwork(FluidIngredient.java:148) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:30) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.SerializerFluidIngredient.fromNetwork(SerializerFluidIngredient.java:17) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.api.recipe.content.IContentSerializer.fromNetworkContent(IContentSerializer.java:43) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at net.minecraft.class_2540.method_34066(class_2540.java:231) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.entryReader(GTRecipeSerializer.java:86) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at net.minecraft.class_2540.method_34068(class_2540.java:218) ~[client-intermediary.jar:?]
	at com.gregtechceu.gtceu.api.recipe.GTRecipeSerializer.fromNetwork(GTRecipeSerializer.java:120) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:36) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.gregtechceu.gtceu.syncdata.GTRecipeAccessor.deserialize(GTRecipeAccessor.java:18) ~[gtceu-fabric-1.20.1-1.0.12.g.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.CustomObjectAccessor.writeManagedField(CustomObjectAccessor.java:62) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ManagedAccessor.writeField(ManagedAccessor.java:52) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writeToReadonlyField(IManagedAccessor.java:120) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.ReadonlyAccessor.writeField(ReadonlyAccessor.java:85) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.field.ManagedKey.writePersistedField(ManagedKey.java:88) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.accessor.IManagedAccessor.writePersistedFields(IManagedAccessor.java:136) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at com.lowdragmc.lowdraglib.syncdata.blockentity.IAutoPersistBlockEntity.loadManagedPersistentData(IAutoPersistBlockEntity.java:35) ~[ldlib-1.0.19.d-e4560248daca0771.jar:?]
	at net.minecraft.class_2586.handler$bed000$ldlib$injectLoad(class_2586.java:1544) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_11014(class_2586.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_2586.method_17897(class_2586.java:132) ~[client-intermediary.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraft.class_2586.method_11005(class_2586.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_2852.method_39797(class_2852.java:408) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:442) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:751) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:739) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:564) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:573) ~[client-intermediary.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:282) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.IOException: Invalid tag id: -128
	at net.minecraft.class_4614$1.method_39878(class_4614.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23264(class_4614.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_4614$1.method_23262(class_4614.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[client-intermediary.jar:?]
	... 50 more
[07:48:35] [Server thread/WARN]: Skipping BlockEntity with id gtceu:lv_chemical_reactor
[07:52:42] [Render thread/INFO]: Reloading pipeline on dimension change: NamespacedId{namespace='minecraft', name='overworld'} => NamespacedId{namespace='minecraft', name='the_nether'}
[07:52:42] [Render thread/INFO]: Destroying pipeline NamespacedId{namespace='minecraft', name='overworld'}
``` 

```

[08:10:33] [Render thread/INFO]: Loaded 553 advancements
[08:10:36] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:old_growth_birch_forest]=net.minecraft.class_1959@e6c020f}]
	at net.minecraft.class_7510.method_44210(class_7510.java:100) ~[client-intermediary.jar:?]
	at net.minecraft.class_2794.method_44215(class_2794.java:102) ~[client-intermediary.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar:?]
	at net.minecraft.class_2794.method_12102(class_2794.java:288) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_51375(class_2806.java:108) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_2806.method_12154(class_2806.java:252) ~[client-intermediary.jar:?]
	at net.minecraft.class_3898.method_17225(class_3898.java:684) ~[client-intermediary.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar:?]
	at net.minecraft.class_3898.method_17224(class_3898.java:673) ~[client-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) ~[client-intermediary.jar:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[08:10:36] [Server thread/ERROR]: This crash report has been saved to: <SNIP>/PrismLauncher/instances/greg's n'd tool's/.minecraft/crash-reports/crash-2023-10-03_08.10.36-server.txt
[08:10:36] [Server thread/INFO]: Stopping server
```

### PR DESCRIPTION
**Pull request by screret**
gotta fix a couple bugs & test first.

### CODE REVIEW

**Comment by screret** [comment]
bugs have been fixed

File: common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/LongDistancePipeBlock.java [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+            offsetPos.set(pos).move(facing);
+            LongDistanceNetwork network = LongDistanceNetwork.get(level, offsetPos);
+            if (network != null && pipeType == network.getPipeType()) {
+                ILDEndpoint endpoint = ILDEndpoint.tryGet(level, offsetPos);
+                // only count the network as connected if it's not an endpoint or the endpoints input or output face is connected
+                if (endpoint == null || endpoint.getFrontFacing().getAxis() == facing.getAxis()) {
+                    networks.add(network);
+                }
+            }
+        }
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/LongDistancePipeBlock.java]: This might benefit from extracting it into a seaparate method.

File: common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/LongDistancePipeType.java [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+    /**
+     * Checks if the given endpoint is a valid endpoint for this type
+     *
+     * @param endpoint potential endpoint
+     * @return if the given endpoint is a valid endpoint for this type
+     */
+    public abstract boolean isValidEndpoint(ILDEndpoint endpoint);
+
+    /**
+     * @return The minimum required distance (not pipe count between endpoints) between to endpoints to work.
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/LongDistancePipeType.java]:
```suggestion
     * @return The minimum required distance (not pipe count) between two endpoints to work.
```

File: common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/NetworkBuilder.java [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+    @Override
+    public void run() {
+        // iterate over each given starting point and try to build a network
+        boolean first = true;
+        while (!starts.isEmpty()) {
+            BlockPos start = starts.pollFirst();
+            if (first) {
+                first = false;
+                checkNetwork(start);
+            } else {
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/api/pipenet/longdistance/NetworkBuilder.java]: consider short circuiting the loop via `continue` instead of an `else` branch

File: common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+        for (Direction facing : Direction.values()) {
+            handlers.put(facing, new ItemNetHandler(net, this, facing));
+        }
+        defaultHandler = new ItemNetHandler(net, this, null);
+    }
+
+    public void checkNetwork() {
+        if (defaultHandler != null) {
+            ItemPipeNet current = getItemPipeNet();
+            if (defaultHandler.getNet() != current) {
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java:71]: consider early returns instead of the nested ifs, for easier readability

File: common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java [hunk 5]
```diff
@@ -0,0 +1,121 @@
...
+                for (ItemNetHandler handler : handlers.values()) {
+                    handler.updateNetwork(current);
+                }
+            }
+        }
+    }
+
+    @Override
+    public boolean canAttachTo(Direction side) {
+        if (level != null) {
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java]: early return might be better here as well

File: common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+            }
+            return ItemTransferHelper.getItemTransfer(level, getBlockPos().relative(side), side.getOpposite()) != null;
+        }
+        return false;
+    }
+
+    @Nullable
+    public ItemPipeNet getItemPipeNet() {
+        if (level instanceof ServerLevel serverLevel && getBlockState().getBlock() instanceof ItemPipeBlock fluidPipeBlock) {
+            ItemPipeNet currentFluidPipeNet = this.currentItemPipeNet.get();
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java]: **[REQUIRED]**  
Wrong variable names. Should be `itemPipeBlock` and `currentItemPipeNet` instead of fluid.

File: common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java [hunk 7]
```diff
@@ -0,0 +1,121 @@
...
+            currentFluidPipeNet = fluidPipeBlock.getWorldPipeNet(serverLevel).getNetFromPos(getBlockPos());
+            if (currentFluidPipeNet != null) {
+                this.currentItemPipeNet = new WeakReference<>(currentFluidPipeNet);
+            }
+        }
+        return this.currentItemPipeNet.get();
+    }
+
+    public void update() {
+        if (++timer % 20 == 0) {
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java:104]: **[REQUIRED]**  
If possible, please consider using `PipeBlockEntity#getOffsetTimer()` instead, so that the load is distributed evenly across ticks.

In case this isn't possible (e.g. if all pipe block entities on the same pipe net need to update in the same tick), it may be possible to add a random offset to each pipenet instead.

File: common/src/main/java/com/gregtechceu/gtceu/common/cover/ConveyorCover.java [hunk 8]
```diff
@@ -59,12 +63,17 @@ public class ConveyorCover extends CoverBehavior implements IUICover, IControlla
...
+    protected DistributionMode distributionMode;
+    @Persisted @DescSynced @Getter
+    protected ManualImportExportMode manualImportExportMode = ManualImportExportMode.DISABLED;
     @Persisted @Getter
     protected boolean isWorkingEnabled = true;
     protected int itemsLeftToTransferLastSecond;
     private Widget ioModeSwitch;
 
     @Persisted @DescSynced
+    @Getter
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/cover/ConveyorCover.java]:
```suggestion
    @Persisted @DescSynced @Getter
```

File: common/src/main/java/com/gregtechceu/gtceu/common/cover/ConveyorCover.java [hunk 9]
```diff
@@ -388,6 +409,18 @@ public Widget createUIWidget() {
...
+                ManualImportExportMode.VALUES, ManualImportExportMode.DISABLED,
+                this::setManualImportExportMode)
+                .setHoverTooltips("cover.universal.manual_import_export.mode.description"));
+
+        if (coverHolder.getLevel().getBlockEntity(coverHolder.getPos()) instanceof ItemPipeBlockEntity ||
+                coverHolder.getLevel().getBlockEntity(coverHolder.getPos().relative(attachedSide)) instanceof ItemPipeBlockEntity) {
+            final EnumSelectorWidget<DistributionMode> distributionModeButton = new EnumSelectorWidget<>(149, 166, 20, 20,
+                    DistributionMode.VALUES, DistributionMode.INSERT_FIRST,
+                    this::setDistributionMode);
+            group.addWidget(distributionModeButton);
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/cover/ConveyorCover.java]:
```suggestion
            group.addWidget(new EnumSelectorWidget<>(149, 166, 20, 20,
                    DistributionMode.VALUES, DistributionMode.INSERT_FIRST,
                    this::setDistributionMode));
```

File: common/src/main/java/com/gregtechceu/gtceu/common/cover/ItemFilterCover.java [hunk 10]
```diff
@@ -23,7 +29,12 @@
 @MethodsReturnNonnullByDefault
 public class ItemFilterCover extends CoverBehavior implements IUICover {
 
+    public static final ManagedFieldHolder MANAGED_FIELD_HOLDER = new ManagedFieldHolder(ItemFilterCover.class, CoverBehavior.MANAGED_FIELD_HOLDER);
+
     protected ItemFilter itemFilter;
+    @Persisted @DescSynced
+    @Getter
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/cover/ItemFilterCover.java]:
```suggestion
    @Persisted @DescSynced @Getter
```

File: common/src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java [hunk 11]
```diff
@@ -229,6 +231,38 @@ public class GTMachines {
...
+            .langValue("Long Distance Fluid Pipeline Endpoint")
+            .rotationState(RotationState.ALL)
+            .tier(LV)
+            .renderer(() -> new TieredHullMachineRenderer(LV, GTCEu.id("block/machine/ld_fluid_endpoint_machine")))
+            .tooltips(Component.translatable("gtceu.machine.endpoint.tooltip.1"),
+                    Component.translatable("gtceu.machine.endpoint.tooltip.2"),
+                    Component.translatable("gtceu.machine.endpoint.tooltip.3"))
+            .tooltipBuilder((stack, tooltip) -> {
+                if (ConfigHolder.INSTANCE.machines.ldItemPipeMinDistance > 0) {
+                    tooltip.add(Component.translatable("gtceu.machine.endpoint.tooltip.min_length", ConfigHolder.INSTANCE.machines.ldItemPipeMinDistance));
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java]: **[REQUIRED]**  
This should use the config option `ldFluidPipeMinDistance` instead of the one for item pipes

File: common/src/main/java/com/gregtechceu/gtceu/common/machine/storage/LongDistanceEndpointMachine.java [hunk 12]
```diff
@@ -0,0 +1,157 @@
...
+
+import java.util.ArrayList;
+import java.util.List;
+
+public abstract class LongDistanceEndpointMachine extends MetaMachine implements ILDEndpoint {
+    protected static final ManagedFieldHolder MANAGED_FIELD_HOLDER = new ManagedFieldHolder(LongDistanceEndpointMachine.class, MetaMachine.MANAGED_FIELD_HOLDER);
+
+    private final LongDistancePipeType pipeType;
+    @Persisted
+    @Getter @Setter
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/machine/storage/LongDistanceEndpointMachine.java]:
```suggestion
    @Persisted @Getter @Setter
```

File: common/src/main/java/com/gregtechceu/gtceu/data/lang/LangHandler.java [hunk 13]
```diff
@@ -695,6 +695,10 @@ public static void init(RegistrateLangProvider provider) {
         provider.add("gtceu.machine.available_recipe_map_2.tooltip", "Available Recipe Maps: %s, %s");
         provider.add("gtceu.machine.available_recipe_map_3.tooltip", "Available Recipe Maps: %s, %s, %s");
         provider.add("gtceu.machine.available_recipe_map_4.tooltip", "Available Recipe Maps: %s, %s, %s, %s");
+        provider.add("gtceu.machine.endpoint.tooltip.1", "Connect with §fLong Distance Pipe§7 blocks to create a pipeline.");
+        provider.add("gtceu.machine.endpoint.tooltip.2", "Pipelines must have exactly §f1 Input§7 and §f1 Output§7 endpoint.");
+        provider.add("gtceu.machine.endpoint.tooltip.3", "Only pipeline endpoints need to be §fchunk-loaded§7.");
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/data/lang/LangHandler.java]: **[REQUIRED]**  
Please use `multiLang()` here instead.

File: common/src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java [hunk 14]
```diff
@@ -0,0 +1,489 @@
...
+        this.world = pipe.getPipeLevel();
+    }
+
+    public void updateNetwork(ItemPipeNet net) {
+        this.net = net;
+    }
+
+    public ItemPipeNet getNet() {
+        return net;
+    }
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: Consider using `@Getter` instead

**Review by mikerooni — CHANGES_REQUESTED** [review]

**Comment by mikerooni** [comment]
The review comments marked with **[REQUIRED]** are necessary, all others are just (optional) suggestions for code quality ^^

File: common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java (hunk 7 above)
Comment (screret) [reply common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java:104]: I don't think a simple modulo operation + assignment needs that TBH.
and yes, they do need to update on the same tick afaik.

Comment (mikerooni) [reply common/src/main/java/com/gregtechceu/gtceu/common/blockentity/ItemPipeBlockEntity.java:104]: True. If this method does more at some point, we can always do that later.

**Review by mikerooni — APPROVED** [review]
lgtm
