### PR TITLE
Ore Maceration Changes

### LINKED ISSUE #3530: Large Miners Output 1x Raw Ore Instead of 3x Crushed Ore
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.2

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Cosmic Frontiers

### Expected Behavior

Large Miners should output 3x Crushed Ore per ore block mined.

### Actual Behavior

Large Miners output 1x Raw Ore per ore block mined.

### Steps to Reproduce

Place down a large miner on an ore vein and run it.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by YoungOnionMC**
## What
Removes the ore stone type transmutation when silk touch grabbing an ore.
Generates maceration and forge hammer recipes for every stone type of each ore, rather than using the intersection ingredient testing.
Fixes #3530 

## Outcome
Using silk touch on a ore will give you the actual block you have mined instead of the stone variant.
Any stone type of an ore can be processed.
mining various stone type ores will give the correct dust drop.

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java [hunk 1]
```diff
@@ -106,29 +104,28 @@ private static void processOre(@NotNull Consumer<FinishedRecipe> provider, @NotN
...
-                    .inputItems(IntersectionIngredient.of(Ingredient.of(orePrefix.getItemTags(material)[0]),
-                            Ingredient.of(orePrefix.getItemParentTags()[0])))
-                    .outputItems(crushedStack.copyWithCount(property.getOreMultiplier() * 2 * oreTypeMultiplier))
+                    .inputItems(inputStack)
+                    .outputItems(crushedStack.copyWithCount(crushedCount * 2))
                     .chancedOutput(byproductStack, 1400, 0)
                     .EUt(2)
-                    .category(GTRecipeCategories.ORE_CRUSHING)
-                    .duration(400);
+                    .duration(400)
```
Comment (DilithiumThoride) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java:127]: Why flip these?

File: src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java [hunk 2]
```diff
@@ -207,13 +200,6 @@ private static void processRawOre(@NotNull Consumer<FinishedRecipe> provider, @N
                     .category(GTRecipeCategories.ORE_CRUSHING)
                     .duration(400);
 
-            for (MaterialStack secondaryMaterial : ore.secondaryMaterials()) {
```
Comment (DilithiumThoride) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java:210]: Are these gem drops accounted for elsewhere or are we just removing them?

**Review by DilithiumThoride — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java (hunk 1 above)
Comment (YoungOnionMC) [reply src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java:127]: it was cleaner imo

File: src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java (hunk 2 above)
Comment (YoungOnionMC) [reply src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java:210]: this was purely for adding the dust drop to grinding raw ore, and imo it made no sense to get the stone dust drop from both the ore block(which has the stone type surrounding the ore) and the raw ore itself(which *should* have no stone type rock around it

Comment (DilithiumThoride) [reply src/main/java/com/gregtechceu/gtceu/data/recipe/generated/OreRecipeHandler.java:210]: Okay actually yeah that makes sense

**Review by DilithiumThoride — APPROVED** [review]

**Review by gustovafing — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/machine/trait/miner/MinerLogic.java [hunk 3]
```diff
@@ -353,19 +353,25 @@ protected boolean doPostProcessing(NonNullList<ItemStack> blockDrops, BlockState
         ItemStack oreDrop = new ItemStack(blockState.getBlock());
         if (oreDrop.isEmpty()) return false;
 
+        outputItemHandler.storage.clear();
+
+        GTRecipe recipe = null; // attempt ore block that has a static gt recipe
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/common/machine/trait/miner/MinerLogic.java]: can this be moved to directly above the while loop? clearer imo

**Review by jurrejelle — DISMISSED** [review]

**Review by Ghostipedia — APPROVED** [review]
