### PR TITLE
Fix crop harvest yielding extra seeds

### LINKED ISSUE #2581: Scythes do not consume the seeds that would otherwise be required to replant a particular crop.
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech Modern Version

v1.5.4

### Minecraft Version

v1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

```groovy
dependencies {
    // Minecraft & Forge
    minecraft "com.mojang:minecraft:$project.minecraft_version"
    forge "net.minecraftforge:forge:$project.minecraft_version-$project.forge_version"
    
    // layered mappings - Mojmap names, parchment and QM docs and parameters
    mappings loom.layered {
        it.mappings("org.quiltmc:quilt-mappings:$project.minecraft_version+build.$project.quilt_mappings:intermediary-v2")
        it.parchment("org.parchmentmc.data:parchment-$project.minecraft_version:$project.parchment_mappings@zip")
        it.officialMojangMappings { nameSyntheticMembers = false }
    }

    // JEI (Version 15.20.0.105) & EMI (Version 1.1.18)
    modCompileOnly("mezz.jei:jei-$project.minecraft_version-forge-api:$project.jei_version") { transitive = false }
    modCompileOnly("mezz.jei:jei-$project.minecraft_version-common-api:$project.jei_version") { transitive = false }
    modRuntimeOnly("mezz.jei:jei-$project.minecraft_version-forge:$project.jei_version") { transitive = false }
    modRuntimeOnly("dev.emi:emi-forge:$project.emi_version+$project.minecraft_version")

    // GT, LdLib, Registrate
    modImplementation("com.gregtechceu.gtceu:gtceu-$project.minecraft_version:$project.gtceu_version") { transitive = false }
    modRuntimeOnly("com.lowdragmc.ldlib:ldlib-forge-$project.minecraft_version:$project.ldlib_version") { transitive = false } // Version 1.0.33.b
    modRuntimeOnly("com.tterrag.registrate:Registrate:$project.registrate_version") // Version MC1.20-1.3.11

    // KubeJS
    modImplementation("dev.latvian.mods:kubejs-forge:$project.kubejs_version") // Version 2001.6.5-build.16

    // Configuration (by Toma1O6)
    modRuntimeOnly("dev.toma.configuration:configuration-forge-$project.minecraft_version:$project.configuration_version") // Version 2.2.0

    // Jade
    modRuntimeOnly("curse.maven:jade-324717:5390389") // Version 11.9.3

    // Mixin Extras (Version 0.2.0)
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:$project.mixinextras_version"))
    implementation(include("io.github.llamalad7:mixinextras-forge:$project.mixinextras_version"))

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.36'
    annotationProcessor 'org.projectlombok:lombok:1.18.36'
}
```

### Expected Behavior

I have a crop with the following loot table:
[magnetite_crop.json](https://github.com/user-attachments/files/18183688/magnetite_crop.json) (ignore the iron nugget entry, it's just a test)

The loot table is configured such that breaking the crop block will only ever drop ONE seed, no matter if the crop is fully grown or not.

I expected that scythes would consume a number of seeds (equal to the number of crops to be replanted) from the amount of seeds that get dropped overall.

### Actual Behavior

https://github.com/user-attachments/assets/857f8a15-5d2a-4367-8a0a-d7255f72f51a

The scythe effectively duplicates the seeds.

### Steps to Reproduce

1) Plant any crop's seed (especially a crop that drops a fixed amount of seeds if broken when fully grown)
2) Wait for the crop to grow.
3) Right the crop with a scythe in hand to use the scythe's harvesting ability.
4) The crops will be replanted, but you will get the normal amount of seeds that would drop from that crop.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by omergunr100**
## What
Our current crop harvest routine creates drops as if the crop was broken, but instead of replanting it using 1 seed it later resets it to age 0, thus breaking the balance of low seed yield crops.

## Implementation Details
When harvesting a crop go over drops and shrink the seed stack by 1.

## Additional Information
Fixes #2581

### CODE REVIEW

**Comment by TheDogOfChaos** [comment]
can confirm that this works: https://github.com/GregTechCEu/GregTech-Modern/issues/2581#issuecomment-2552061277

File: src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/HarvestCropsBehavior.java [hunk 1]
```diff
@@ -93,15 +91,25 @@ private static boolean isBlockCrops(ItemStack stack, Level world, Player player,
...
+            final var check = new boolean[] { true };
+            var drops = Block.getDrops(blockState, (ServerLevel) level, pos, null).stream()
+                    .peek(itemStack -> {
+                        if (check[0] && itemStack.is(seed)) {
+                            itemStack.shrink(1);
+                            check[0] = false;
+                        }
+                    })
+                    .filter(itemStack -> itemStack.getCount() > 0)
+                    .toList();
```
Comment (krossgg) [inline src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/HarvestCropsBehavior.java]: As an avid user of streams: this is cursed. Just use a `listIterator` of the drops to search for the seed stack, then remove it if empty after the shrink. Then break.

**Review by krossgg — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/HarvestCropsBehavior.java [hunk 2]
```diff
@@ -93,15 +91,26 @@ private static boolean isBlockCrops(ItemStack stack, Level world, Player player,
...
+        var cropBlock = (CropBlock) block;
+        final var seed = cropBlock.getCloneItemStack(level, pos, blockState).getItem();
+        if (cropBlock.isMaxAge(blockState)) {
+            var drops = Block.getDrops(blockState, (ServerLevel) level, pos, null);
+            for (int i = 0; i < drops.size(); i++) {
+                var drop = drops.get(i);
+                if (drop.is(seed)) {
+                    drop.shrink(1);
+                    if (drop.isEmpty()) {
+                        drops.remove(drop);
```
Comment (krossgg) [inline src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/HarvestCropsBehavior.java]:
```suggestion
                        drops.remove(i);
```
You already know the index - its the current one, remove via index instead of forcing a search through the list.

**Review by krossgg — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/HarvestCropsBehavior.java (hunk 2 above)
Comment (omergunr100) [reply src/main/java/com/gregtechceu/gtceu/common/item/tool/behavior/HarvestCropsBehavior.java]: I switched it to an iterator

**Review by krossgg — APPROVED** [review]
