### PR TITLE
fixes 5: the bugs strike back

### LINKED ISSUE #859: Crash when starting the game
### GregTech CEu Version

gtceu-1.19.2-1.1.2

### Recipe Viewer Installed

None

### Environment

 Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

starting game

### Actual Behavior

carsh

### Steps to Reproduce

start game with modpacks

### Additional Information

[minecraft-exported-crash-info-2024-01-31T10-51-46.zip](https://github.com/GregTechCEu/GregTech-Modern/files/14106659/minecraft-exported-crash-info-2024-01-31T10-51-46.zip)

### LINKED ISSUE #865: GT powered Wrenches/Screwdrivers do not work
### GregTech CEu Version

1.1.2.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

I expect the powered tools to have the same functions as the unpowered versions.

### Actual Behavior

The powered Wrench and Screwdriver do not show the overlay for editing pipes/machines, nor does it work if you try to click in the right spot.

### Steps to Reproduce

Place down some pipes, try to configure with a powered Wrench.
Place down a machine or Crate, try to configure with a powered Screwdriver.

### Additional Information

Other unpowered wrenches from GT and other mods do work as intended.

### PR DESCRIPTION
**Pull request by screret**

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/item/tool/GTToolType.java [hunk 1]
```diff
@@ -374,10 +375,12 @@ public class GTToolType {
     public final ToolConstructor constructor;
     public final int electricTier;
 
-    public GTToolType(String name, String idFormat, Character symbol, IGTToolDefinition toolDefinition, ToolConstructor constructor, List<TagKey<Block>> harvestTags, List<TagKey<Item>> itemTags, ResourceLocation modelLocation, Set<String> toolClassNames, @Nullable SoundEntry soundEntry, boolean playSoundOnBlockDestroy, int electricTier) {
+    public GTToolType(String name, String idFormat, Character symbol, Set<GTToolType> toolClasses, IGTToolDefinition toolDefinition, ToolConstructor constructor, List<TagKey<Block>> harvestTags, List<TagKey<Item>> itemTags, ResourceLocation modelLocation, Set<String> toolClassNames, @Nullable SoundEntry soundEntry, boolean playSoundOnBlockDestroy, int electricTier) {
         this.name = name;
         this.idFormat = idFormat;
         this.symbol = symbol;
+        toolClasses.add(this);
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/api/item/tool/GTToolType.java:382]: I'd recommend doing this in the Tool Type Builder's `build()` or `get()` method instead if possible, since this basically introduces an out-parameter.

File: src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java [hunk 2]
```diff
@@ -1561,26 +1570,25 @@ public static BiConsumer<ItemStack, List<Component>> createTankTooltips(String n
...
-                                    .or(Predicates.abilities(PartAbility.OUTPUT_ENERGY))
+                            .where('X', blocks(ProcessingArrayMachine.getCasingState(tier))
+                                    .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setPreviewCount(1))
+                                    .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setPreviewCount(1))
+                                    .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setPreviewCount(1))
+                                    .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setPreviewCount(1))
+                                    .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setMinGlobalLimited(1).setMaxGlobalLimited(4).setPreviewCount(1))
+                                    .or(Predicates.abilities(PartAbility.MACHINE_HATCH).setExactLimit(1))
                                     .or(Predicates.autoAbilities(true, false, false)))
-                            .where('C', blocks(CLEANROOM_GLASS.get()))
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java:1576]: Why remove the cleanroom glass? (this may break a lot of existing builds)

I think it may be better to have this be an option instead tbh.

File: src/main/java/com/gregtechceu/gtceu/utils/GTUtil.java [hunk 3]
```diff
@@ -396,6 +398,30 @@ public static FluidStack getFluidFromContainer(Object ingredient) {
...
+    public static boolean isMachineValidForMachineHatch(ItemStack machineStack, GTRecipeType[] recipeTypeBlacklist) {
+        if (machineStack == null || machineStack.isEmpty()) {
+            return false;
+        }
+
+        if (machineStack.getItem() instanceof MetaMachineItem metaMachineItem) {
+            MachineDefinition definition = metaMachineItem.getDefinition();
+            IMachineBlockEntity be = MetaMachineBlockEntity.createBlockEntity(definition.getBlockEntityType(), BlockPos.ZERO, definition.defaultBlockState());
+            MetaMachine machine = be.getMetaMachine();
+            if (machine instanceof WorkableTieredMachine && !(machine instanceof SimpleGeneratorMachine)) {
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/utils/GTUtil.java]: I think it might be better to add an additional method for this check in the machine class instead, just so that addon devs can override that if necessary.  
Something like `isAllowedInProcessingArray()` maybe.

Not sure if this is fully covered by the recipe type blacklist already. Could have some edge cases here where a dummy recipe and custom recipe logic is used in addons.

File: src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java (hunk 2 above)
Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java:1576]: because it made the structure like 30% cheaper.

Comment (mikerooni) [reply src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java:1576]: True, but it also limited the IO options quite a bit in return.

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java:1576]: also really dumb IMO.

File: src/main/java/com/gregtechceu/gtceu/api/item/tool/GTToolType.java (hunk 1 above)
Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/api/item/tool/GTToolType.java:382]: couldn't easily, tried though

File: src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java (hunk 2 above)
Comment (mikerooni) [reply src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java:1576]: Hmm not sure tbh. Do you think there's a way to keep the previous design with the cleanroom glass while balancing it better?

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java:1576]: there never was any good reason to have it be like that other than adding a machine render to it. it just limited precious IO whilst making the structure a lot cheaper.

Comment (mikerooni) [reply src/main/java/com/gregtechceu/gtceu/common/data/GTMachines.java:1576]: Note that this is just my personal taste here mostly.  
I liked the previous design quite a lot and think it looks pretty cool compared to the 1.12 PA - but I can also understand why you would want to use this design instead.

Would love to have this a config option at least.

**Review by mikerooni — APPROVED** [review]
