### PR TITLE
Fix pattern encoding for multiblock preview in EMI

### LINKED ISSUE #2463: EMI does not support "Fill Recipe" on multiblock preview for AE2 processing pattern
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.5.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Applied Energistics 2

### Expected Behavior

EMI is able to "Fill Recipe" from the multiblock preview into an AE2 processing pattern

### Actual Behavior

EMI is not able to "Fill Recipe" from the multiblock preview into an AE2 processing pattern
image

### Steps to Reproduce

1) Open a pattern encoding terminal
2) Open a multiblock preview (e.g. Electric Blast furnace)
3) Hover over "Fill Recipe" button
4) EMI displays "Current workstation does not support recipe"

### Additional Information

This behavior works as expected on JEI

### PR DESCRIPTION
**Pull request by kitgxrl**
## What
Allows for encoding multiblocks into a processing pattern

## Implementation Details
simply checks for instanceof `MultiblockInfoEmiRecipe` in `supportsRecipe`

## Outcome
Fixes: #2463

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/integration/emi/recipe/Ae2PatternTerminalHandler.java [hunk 1]
```diff
@@ -37,7 +37,7 @@ public EmiPlayerInventory getInventory(AbstractContainerScreen<T> screen) {
 
     @Override
     public boolean supportsRecipe(EmiRecipe recipe) {
-        return recipe instanceof GTEmiRecipe;
+        return recipe instanceof GTEmiRecipe | recipe instanceof MultiblockInfoEmiRecipe;
```
Comment (krossgg) [inline src/main/java/com/gregtechceu/gtceu/integration/emi/recipe/Ae2PatternTerminalHandler.java]: Use the short-circuiting operator `||`, also you forgot to import the class??

**Review by krossgg — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/integration/emi/recipe/Ae2PatternTerminalHandler.java (hunk 1 above)
Comment (kitgxrl) [reply src/main/java/com/gregtechceu/gtceu/integration/emi/recipe/Ae2PatternTerminalHandler.java]: Yep, forgot to import the class, my bad. `|` was also a typo lol

**Review by krossgg — APPROVED** [review]
