### PR TITLE
Fix Ranged Fluid Ingredients deserializing incorrectly in SMP

### LINKED ISSUE #4141: Ranged Fluid Ingredients display incorrectly but only in SMP
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.2.1

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Multiplayer - Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

Monifactory 0.13

### Expected Behavior

Image

### Actual Behavior

Image

### Steps to Reproduce

Launch client (and server)
**Do Not** open a Singleplayer world
Connect to server, check EMI

### Additional Information

I have a pretty solid hunch this is because I wrote the netcode for IPFI wrong because EMI is incorrectly getting handed the ingredient as just a straight FluidIngredient.

What's extremely weird is that loading SSP causes the bug to be fixed and not occur until the client is restarted.

Unfortunately there's also a bunch of LDLib and MUI in the call stack which means the moment we hit 8.0.0 this will all be different. Maybe I should try to reproduce using Gustavo's Sync branch and see what happens.

### PR DESCRIPTION
**Pull request by DilithiumThoride**
## What
fixes #4141
IntProviderFluidIngredients were not being properly deserialized from network in SMP, causing them to display in EMI as their max value, not as a range

## Implementation Details
Establishes a small Registry of FluidIngredient subclasses and their fromNetwork() methods. Upon calling toNetwork, serializes the class name before the main data, then on deserialize reads that class name and uses that to reference the registry

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java [hunk 1]
```diff
@@ -226,4 +234,17 @@ public CompoundTag toNBT() {
...
+        buffer.writeCollection(SERIALIZEMARKERLIST, FriendlyByteBuf::writeVarInt);
+        inner.toNetwork(buffer);
+        buffer.writeVarIntArray(new int[] { countProvider.getMinValue(), countProvider.getMaxValue() });
+    }
+
+    public static IntProviderFluidIngredient fromNetwork(FriendlyByteBuf buffer) {
+        FluidIngredient readI = FluidIngredient.fromNetwork(buffer);
+        int[] readC = buffer.readVarIntArray(2);
+        IntProvider readP = UniformInt.of(readC[0], readC[1]);
+        return new IntProviderFluidIngredient(readI, readP);
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java]: Can these variables get more clear names? :)

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/FluidIngredient.java [hunk 2]
```diff
@@ -252,7 +252,14 @@ public static FluidIngredient of(TagKey<Fluid> tag, int amount, @Nullable Compou
     }
 
     public static FluidIngredient fromNetwork(FriendlyByteBuf buffer) {
-        List<Fluid> fluids = buffer.readList(buf -> buf.readById(BuiltInRegistries.FLUID));
+        List<Integer> preFluids = buffer.readList(FriendlyByteBuf::readVarInt);
+        if (preFluids.get(0) == IntProviderFluidIngredient.SERIALIZAZTIONMARKER)
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/FluidIngredient.java]: This will throw an indexOutOfBounds error if preFluids is empty, can we add a check for that? (e.g. if preFluids.size() > 0 && ...

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java [hunk 3]
```diff
@@ -226,4 +234,17 @@ public CompoundTag toNBT() {
...
+    public void toNetwork(FriendlyByteBuf buffer) {
+        buffer.writeCollection(SERIALIZEMARKERLIST, FriendlyByteBuf::writeVarInt);
+        inner.toNetwork(buffer);
+        buffer.writeVarIntArray(new int[] { countProvider.getMinValue(), countProvider.getMaxValue() });
+    }
+
+    public static IntProviderFluidIngredient fromNetwork(FriendlyByteBuf buffer) {
+        FluidIngredient readI = FluidIngredient.fromNetwork(buffer);
+        int[] readC = buffer.readVarIntArray(2);
+        IntProvider readP = UniformInt.of(readC[0], readC[1]);
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java]: This means we can only (de)serialize uniform countproviders, do we support any others?

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java [hunk 4]
```diff
@@ -32,6 +35,11 @@ public class IntProviderFluidIngredient extends FluidIngredient {
 
     public static final Codec<IntProviderFluidIngredient> CODEC = ExtraCodecs.JSON
             .xmap(IntProviderFluidIngredient::fromJson, IntProviderFluidIngredient::toJson);
+    /**
+     * "ipfi" as hex. Used to tell {@link FluidIngredient#fromNetwork(FriendlyByteBuf)} to deserialize as an IPFI.
+     */
+    public static final int SERIALIZAZTIONMARKER = -69706669;
+    private static final List<Integer> SERIALIZEMARKERLIST = List.of(SERIALIZAZTIONMARKER);
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java]: thoughts on changing this to SERIALIZATION_MARKER and SERIALIZATION_MARKER_LIST for clarity?

**Review by jurrejelle — DISMISSED** [review]

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java (hunk 3 above)
Comment (DilithiumThoride) [reply src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java]: In this context, we actually don't need to. To/From Network is only used to send data to the client. The client doesn't do the rolls for IPFI values so it doesn't need to know exactly how the roll is made, it just needs to know that there is a range so it can display it.

Comment (jurrejelle) [reply src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/IntProviderFluidIngredient.java]: image
It seems all CountProviders have a MinValue and MaxValue, seems fine then

File: src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/FluidIngredient.java [hunk 5]
```diff
@@ -252,7 +252,14 @@ public static FluidIngredient of(TagKey<Fluid> tag, int amount, @Nullable Compou
     }
 
     public static FluidIngredient fromNetwork(FriendlyByteBuf buffer) {
-        List<Fluid> fluids = buffer.readList(buf -> buf.readById(BuiltInRegistries.FLUID));
+        List<Integer> preFluids = buffer.readList(FriendlyByteBuf::readVarInt);
+        if (!preFluids.isEmpty() && preFluids.get(0) == IntProviderFluidIngredient.SERIALIZATION_MARKER)
+            return IntProviderFluidIngredient.fromNetwork(buffer);
```
Comment (krossgg) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/FluidIngredient.java]: Add brackets :^)

Comment (jurrejelle) [reply src/main/java/com/gregtechceu/gtceu/api/recipe/ingredient/FluidIngredient.java]: This code will be removed when #4151 is merged into it luckily

File: src/main/java/com/gregtechceu/gtceu/api/recipe/content/SerializerFluidIngredient.java [hunk 6]
```diff
@@ -1,27 +1,50 @@
...
+        FLUID_SERIALIZERS.register("IntProviderFluidIngredient", IntProviderFluidIngredient::fromNetwork);
+    };
+
     private SerializerFluidIngredient() {}
 
     @Override
     public void toNetwork(FriendlyByteBuf buf, FluidIngredient content) {
+        String name = content.getClass().getSimpleName();
+        if (!FLUID_SERIALIZERS.containKey(name)) {
+            throw new IllegalArgumentException(
```
Comment (krossgg) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/content/SerializerFluidIngredient.java]: Technically this would be more of an `IllegalStateException`, but just a nitpick

**Review by Ghostipedia — APPROVED** [review]
