### PR TITLE
Fix Robot Arm Keep Exact functionality with item pipes

### LINKED ISSUE #2799: Robot Arms filtering on keep exact still not working
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.6.4

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

JEI

### Environment

Multiplayer - Dedicated Server

### Cross-Mod Interaction

No

### Other Installed Mods

ATM9 modpack
This goes way back and was never fixed in Nomifactory or GTNH (in those cases items could be voided if transfer rate > 1 and not a divisor of
filtered counts)

### Expected Behavior

Using a robot arm on keep exact mode with a filter on whitelist (either on pipe with extract or on machine with inport).
At least two distinct items, say A and B, in the whitelist, each with a specified count (equal or not), say X and Y.
Target inventory/machine should receive exactly X amount of item A and Y amount of item B.

### Actual Behavior

The first considered count (last in reading order in the filter IIRC) acts as the amount of total items.
Say X is considered, the machine receives a total of X items in an arbitrary combinations (whichever are supplied first) of items A and B.
Y is ignored.
The behaviour is normal if only one item is filtered, but as soon as two items are filtered one starts to see this issue.

### Steps to Reproduce

A good test example would be the sulfur dust+raw rubber dust recipe in a chemical reactor.
Setup a chemical reactor (CR) and two input sources (chests with conveyors or machines with auto output), one with sulfur dust,
the other with raw rubber dust. Connect all 3 with item pipes.
Setup a robot arm, either on the CR in import mode, or on a pipe at the CR in export mode (bug happens in both cases).
Set the robot arm in keep exact mode.
Add a whitelist filter to the robot arm with both sulfur dust and raw rubber dust with their respective counts.
(either same counts, say 32 and 32 or distinct counts, say 2 and 18)

### Additional Information

This is likely caused by an algorithmic error when looping through filtered items while book-keeping
transfered item amounts and checking against per-item exact counts.

### PR DESCRIPTION
**Pull request by BryanSer**
## What
Fixes #2799 
This PR fixes an item count calculation issue in RobotArmCover's KEEP_EXACT transfer mode. The previous implementation didn't properly verify if the items being moved matched the target slot's contents, leading to incorrect item quantity returns.

## Implementation Details
- Removed the redundant `isStackSpecific` parameter from `countStack` method  
- Revised item matching logic to require both:  
  - ItemStack matching (using `ItemStackHashStrategy.comparingAllButCount`)  
  - Filter test from RobotArmCover  
- Simplified conditional checks in item counting logic  

## Outcome
- Correctly verifies item type matches before counting items in destination container  
- Ensures RobotArmCover's KEEP_EXACT mode only counts matching items that pass its filter

### CODE REVIEW

**Review by omergunr100 — CHANGES_REQUESTED** [review]
logic looks good but run `spotlessApply`

**Review by omergunr100 — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java [hunk 1]
```diff
@@ -365,14 +365,14 @@ public CoverBehavior getCoverOnNeighbour(BlockPos pos, Direction handlerFacing)
...
         int rate;
-        boolean isStackSpecific = false;
         rate = arm.getFilterHandler().getFilter().testItemCount(stack);
         int count;
         switch (arm.getTransferMode()) {
             case TRANSFER_ANY:
                 return insert(handler, stack, simulate, allowed, ignoreLimit);
             case KEEP_EXACT:
-                count = rate - countStack(handler, stack, arm, isStackSpecific);
+                boolean isSupportAmounts = !arm.getFilterHandler().getFilter().supportsAmounts();
```
Comment (umajho) [inline src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: Hello. Why is this variable called `isSupportAmounts` while it uses the inversion of `.supportsAmounts()`'s result?
If the result is inverted, wouldn't it be called something like `doesNotSupportAmounts`?

Comment (omergunr100) [reply src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: True, I did miss it, it would be best to just pull that logic out of `countStack` and have something like:
```java
if(arm.getFilterHandler().getFilter().supportsAmounts()) {
    count = rate - countStack(handler, stack, arm);
} else {
    count = rate;
}
```

**Review by omergunr100 — CHANGES_REQUESTED** [review]

**Comment by BryanSer** [comment]
I'll fix it tonight, thanks for feedback.

**Review by omergunr100 — APPROVED** [review]

**Review by umajho — APPROVED** [review]

**Comment by umajho** [comment]
I can confirm that KEEP_EXACT works with multiple filtered items now. Thank you.
I believe that this fix will benefit processing line design a lot. I'm gonna replace the jar included in the modpack I'm playing with the one built from this PR immediately, so that I don't need to wait for the next release.

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java [hunk 2]
```diff
@@ -393,13 +396,13 @@ public ItemStack insertOverRobotArm(IItemHandler handler, RobotArmCover arm, Ite
...
 
-    public static int countStack(IItemHandler handler, ItemStack stack, RobotArmCover arm, boolean isStackSpecific) {
+    public static int countStack(IItemHandler handler, ItemStack stack, RobotArmCover arm) {
         if (arm == null) return 0;
         int count = 0;
         for (int i = 0; i < handler.getSlots(); i++) {
             ItemStack slot = handler.getStackInSlot(i);
             if (slot.isEmpty()) continue;
-            if (isStackSpecific ? ItemStackHashStrategy.comparingAllButCount().equals(stack, slot) :
+            if (ItemStackHashStrategy.comparingAllButCount().equals(stack, slot) &&
```
Comment (krossgg) [inline src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: Don't use ItemStackHashStrategy to compare two stacks, switch this to use one of the ItemStack methods, I think `isSameItemSameTags` but look around.

**Review by krossgg — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java (hunk 2 above)
Comment (BryanSer) [reply src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: Ok, I'll change it.
By the way, should I use the filter setting to compare item?
Because player can set filter to ignore NBT.

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java [hunk 3]
```diff
@@ -399,11 +400,22 @@ public ItemStack insertOverRobotArm(IItemHandler handler, RobotArmCover arm, Ite
...
         int count = 0;
+        ItemFilter filter = arm.getFilterHandler().getFilter();
         for (int i = 0; i < handler.getSlots(); i++) {
             ItemStack slot = handler.getStackInSlot(i);
             if (slot.isEmpty()) continue;
-            if (ItemStackHashStrategy.comparingAllButCount().equals(stack, slot) &&
-                    arm.getFilterHandler().getFilter().test(slot)) {
+            boolean ignoreNBT;
+            if (filter instanceof SimpleItemFilter) {
+                ignoreNBT = ((SimpleItemFilter) filter).isIgnoreNbt();
```
Comment (omergunr100) [inline src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: A bit of a nitpick so I apologize in advance, but when you check for `instanceof` you can assign it to a variable to avoid casting again (just a style choice):
```java
if(filter instanceof SimpleItemFilter simpleFilter) {
    ignoreNBT = simpleFilter.isIgnoreNbt();
}
```
or even replace the whole `if-else` block with:
```java
boolean ignoreNBT = filter instanceof SimpleItemFilter simple && simple.isIgnoreNbt();
```

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java [hunk 4]
```diff
@@ -365,14 +366,17 @@ public CoverBehavior getCoverOnNeighbour(BlockPos pos, Direction handlerFacing)
     public ItemStack insertOverRobotArm(IItemHandler handler, RobotArmCover arm, ItemStack stack, boolean simulate,
                                         int allowed, boolean ignoreLimit) {
         int rate;
-        boolean isStackSpecific = false;
         rate = arm.getFilterHandler().getFilter().testItemCount(stack);
```
Comment (omergunr100) [inline src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: Assign the value at declaration

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java [hunk 5]
```diff
@@ -399,11 +400,22 @@ public ItemStack insertOverRobotArm(IItemHandler handler, RobotArmCover arm, Ite
...
             if (slot.isEmpty()) continue;
-            if (ItemStackHashStrategy.comparingAllButCount().equals(stack, slot) &&
-                    arm.getFilterHandler().getFilter().test(slot)) {
+            boolean ignoreNBT;
+            if (filter instanceof SimpleItemFilter) {
+                ignoreNBT = ((SimpleItemFilter) filter).isIgnoreNbt();
+            } else {
+                ignoreNBT = false;
+            }
+            if (ignoreNBT && !ItemStack.isSameItemSameTags(stack, slot)) {
```
Comment (omergunr100) [inline src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: I'm not sure the first condition does what it should, we want to continue if the NBT isn't ignored and the items can't stack or if the NBT is ignored and the items aren't the same.
So I think it should look something like:
```java
if (ignoreNBT) {
    if (!slot.is(stack.getItem())) {
        continue;
    }
} else if (!ItemHandlerHelper.canItemStacksStack(stack, slot)) {
    continue;
}
```
As it is currently you check for NBT tag equality even in the case where NBT is ignored, all we should care about is item equality afaik.

Feel free to correct me if I'm misreading that.

**Review by omergunr100 — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java (hunk 3 above)
Comment (krossgg) [reply src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: +1 for the single line expression - but pull it out to L403, before the for loop.

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java (hunk 5 above)
Comment (krossgg) [reply src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]:
```java
if (ignoreNBT && !ItemStack.isSameItem(stack, slot)) continue;
else if (!ItemStack.isSameItemSameTags(stack, slot)) continue;
```
Don't need to nest in this instance, as sameItemSameTags is a subset of isSameItem
I noticed that the SimpleItemFilter also does this incorrectly - if you want to fix that in this PR feel free.

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java (hunk 3 above)
Comment (BryanSer) [reply src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: Sorry, I have become accustomed to writing kotlin, and the java style has been somewhat forgotten.

File: src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java (hunk 5 above)
Comment (BryanSer) [reply src/main/java/com/gregtechceu/gtceu/common/pipelike/item/ItemNetHandler.java]: Done. I've also fixed the comparison issues in SimpleItemFilter together.

**Review by krossgg — APPROVED** [review]

**Review by omergunr100 — APPROVED** [review]

**Review by krossgg — APPROVED** [review]
