### PR TITLE
prepare for release

### LINKED ISSUE #549: GTCEu tools are not working correctly
### GregTech CEu Version

gtceu-forge-1.20.1-1.0.15.a-build_288.jar

### Recipe Viewer Installed

REI

### Environment

Singleplayer, Multiplayer

### Cross-Mod Interaction

Unsure

### Expected Behavior

When you press RBM with an axe in your hand on a log block, it should clear the bark, but this does not happen, the same thing happens with cleaning the block from honey and rust.

Same with shovels and paths.

### Actual Behavior

I have to be able to peel the honey off the copper block, peel the rust off the copper block, and peel the bark off the log block.

### Steps to Reproduce

1) Install GTCEU
2) Enter the world
3) Try make path, or anything else described in the topic

### Additional Information

_No response_

### LINKED ISSUE #562: Missing Recipes on Initial World Load
### GregTech CEu Version

1.20.1-1.0.15.a

### Recipe Viewer Installed

JEI

### Environment

Singleplayer and Dedicated Server

### Cross-Mod Interaction

No

### Expected Behavior

After placing down a distillery being able to craft benzene from Wood Tar.

### Actual Behavior

All recipes for benzene are missing from the distillery, except 1 (heavy fuel).  The recipes are not just missing from JEI, they dont actually function in the machine.

### Steps to Reproduce

Create a pack with just GTCEU and JEI with Forge 4.2.0 (also tried 4.1.3 and 4.2.6).
Load world for the first time, look up recipes for benzene.
Do /reload and then check the recipes again.

### Additional Information

This issue seems to only happen on initial world load.  After leaving and rejoining (singleplayer) or doing /reload, the issue is resolved.

### LINKED ISSUE #563: Dedicated server crashes on startup when Epic fight with gtceu higher than 1.0.13e installed
### GregTech CEu Version

higher than 1.0.13e (MC 1.20.1)

### Recipe Viewer Installed

JEI

### Environment

Dedicated server only

### Cross-Mod Interaction

Yes

### Expected Behavior

Server starts without crashes

### Actual Behavior

Crash occurs

### Steps to Reproduce

1) Install neoforge server 1.20.1 47.1.79
2) Install GTCEu modern higher than 1.20.1 1.0.13e version
3) Install [EpicFight-20.5.17](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/4861795)
4) Try to run dedicated server

### Additional Information

Latest log:
https://mclo.gs/hlTyNoW
Crash report:
https://mclo.gs/DpEXAB5

### PR DESCRIPTION
**Pull request by screret**
fixes #563 
fixes #562 
fixes #549

### CODE REVIEW

File: common/src/main/java/com/gregtechceu/gtceu/api/item/GTToolItem.java [hunk 1]
```diff
@@ -102,16 +114,136 @@ public InteractionResult onItemUseFirst(ItemStack itemStack, UseOnContext contex
...
+        } else {
+            Player player = context.getPlayer();
+            BlockState blockState2 = ShovelItem.FLATTENABLES.get(blockState.getBlock());
+            BlockState blockState3 = null;
+            if (blockState2 != null && level.getBlockState(blockPos.above()).isAir()) {
+                level.playSound(player, blockPos, SoundEvents.SHOVEL_FLATTEN, SoundSource.BLOCKS, 1.0F, 1.0F);
+                blockState3 = blockState2;
+            } else if (blockState.getBlock() instanceof CampfireBlock && blockState.getValue(CampfireBlock.LIT)) {
+                if (!level.isClientSide()) {
+                    level.levelEvent(null, 1009, blockPos, 0);
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/api/item/GTToolItem.java]: In case `1009` is declared as a constant somewhere, it would be better to use here than a magic value.  
Otherwise, I think the context should be enough to know what it is.

File: common/src/main/java/com/gregtechceu/gtceu/api/item/GTToolItem.java [hunk 2]
```diff
@@ -102,16 +114,136 @@ public InteractionResult onItemUseFirst(ItemStack itemStack, UseOnContext contex
...
+        Optional<BlockState> waxable = Optional.ofNullable(HoneycombItem.WAX_OFF_BY_BLOCK.get().get(blockState.getBlock()))
+                .map(block -> block.withPropertiesOf(blockState));
+        ItemStack itemStack = context.getItemInHand();
+        Optional<BlockState> result = Optional.empty();
+        if (strippable.isPresent()) {
+            level.playSound(player, blockPos, SoundEvents.AXE_STRIP, SoundSource.BLOCKS, 1.0F, 1.0F);
+            result = strippable;
+        } else if (cleanable.isPresent()) {
+            level.playSound(player, blockPos, SoundEvents.AXE_SCRAPE, SoundSource.BLOCKS, 1.0F, 1.0F);
+            level.levelEvent(player, 3005, blockPos, 0);
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/api/item/GTToolItem.java]: same here

File: common/src/main/java/com/gregtechceu/gtceu/api/item/GTToolItem.java [hunk 3]
```diff
@@ -102,16 +114,136 @@ public InteractionResult onItemUseFirst(ItemStack itemStack, UseOnContext contex
...
+            result = cleanable;
+        } else if (waxable.isPresent()) {
+            level.playSound(player, blockPos, SoundEvents.AXE_WAX_OFF, SoundSource.BLOCKS, 1.0F, 1.0F);
+            level.levelEvent(player, 3004, blockPos, 0);
```
Comment (mikerooni) [inline common/src/main/java/com/gregtechceu/gtceu/api/item/GTToolItem.java]: as well as here

**Review by mikerooni — APPROVED** [review]

**Review by mikerooni — APPROVED** [review]
