### PR TITLE
The most minor of model fixes

### LINKED ISSUE #3338: Visual issues with primitive pump post rewrite
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.0-SNAPSHOT+5285264

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Embeddium, ModernFix, Jade, AE2

### Expected Behavior

To not look like this

### Actual Behavior

it looks like this

Image

has been reported before but since it's the same multi, also the controller has a visual bug

Image

### Steps to Reproduce

Build the Primitive Pump multi and see

### Additional Information

_No response_

### LINKED ISSUE #3339: Creative energy and Creative Computation Provider missing overlays
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.0-SNAPSHOT+5285264

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Embeddium, ModernFix, Jade, AE2

### Expected Behavior

Image
1.6.4 (from left to right)
Creative Energy
Creative Computation Provider
Creative Data Acess Hatch

### Actual Behavior

Snapshot (i think data access hatch looks fine just posting in case there is something i'm not seeing)

Image

### Steps to Reproduce

Place all the blocks and look

### Additional Information

_No response_

### LINKED ISSUE #3344: Active Multiblock overlay isn't showing
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.0-SNAPSHOT+5285264

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Embeddium, ModernFix, Jade, AE2

### Expected Behavior

The Green looking overlay on machines instead of the red one like the one on the Large Miner 

### Actual Behavior

LCR doing a recipe

Image

Large Elite Miner running

Image

### Steps to Reproduce

Place the multiblocks. Run them, look at controller not having the overlay

### Additional Information

on the LCR the coil does lit up

### PR DESCRIPTION
**Pull request by screret**
## What
fixes #3338 
fixes the steam input hatch having a missing texture on the front

### CODE REVIEW

**Comment by Pumpkin7266** [comment]
image
pump hatch doesn't seem fixed. Rest of the models are though.

**Comment by screret** [comment]
I can't do much about the pump hatch, as if I make the back face have the rock texture, placing it facing down will have the wrong texture.

**Review by Ghostipedia — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/client/model/machine/MachineModel.java [hunk 1]
```diff
@@ -272,17 +302,20 @@ public List<BakedQuad> renderMachine(@Nullable MetaMachine machine, @Nullable Bl
         MachineRenderState renderState = machine != null ? machine.getRenderState() : definition.defaultRenderState();
         renderBaseModel(quads, renderState, blockState, side, rand, modelData, renderType);
 
-        if (machine instanceof IMultiPart part && part.replacePartModelWhenFormed()) {
-            quads = replacePartBaseModel(quads, part, frontFacing, side, rand, modelData, renderType);
-        }
         if (machine != null) {
+            for (DynamicRender render : dynamicRenders) {
+                render.getRenderQuads(machine, blockState, side, rand, modelData, renderType);
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/client/model/machine/MachineModel.java]: Is the return value ignored here on purpose?

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/client/model/machine/MachineModel.java]: uh, no

File: src/main/java/com/gregtechceu/gtceu/utils/data/RuntimeExistingFileHelper.java [hunk 2]
```diff
@@ -55,7 +51,7 @@ protected ResourceLocation getLocation(ResourceLocation base, String prefix, Str
 
     @Override
     public boolean exists(ResourceLocation loc, PackType packType) {
-        return generated.get(packType).contains(loc) || getManager(packType).getResource(loc).isPresent();
+        return true;
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/utils/data/RuntimeExistingFileHelper.java:54]: Doesn't this strip logic that's needed?

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/utils/data/RuntimeExistingFileHelper.java:54]: no, the resource manager isn't actually loaded yet so all it did was throw an error.

**Review by jurrejelle — APPROVED** [review]
