### PR TITLE
Fix GTRecipeBuilder ranged item outputs

### LINKED ISSUE #3267: Ranged Item Output defined via GTRecipeBuilder throws "Output item is not one of"
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

latest git pull

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

blank dev instance

### Expected Behavior

Creating a recipe using the following test definition
`        CENTRIFUGE_RECIPES.recipeBuilder("ranged_hydrogen")
                .inputFluids(Naphthalene.getFluid(1000))
                .outputItems(ingot, Steel, 1)
                .outputItemsRanged(new ItemStack(Blocks.SAND), UniformInt.of(1, 4))
                .outputFluids(Oxygen.getFluid(500))
                .duration(100).EUt(1).save(provider);
`
creates a recipe which outputs at random 1-4 Sand.

Creating this recipe using kube.js works as expected

### Actual Behavior

Recipe is created but Sand isn't in it, and the error log contains the line
`Output item is not one of:
Item, Supplier<Item>, ItemStack, Ingredient, MaterialEntry, TagKey<Item>, MachineDefinition, id: gtceu:ranged_hydrogen`

### Steps to Reproduce

the above code things

### Additional Information

Found this bug while trying to test add Ranged _Fluid_ Outputs to recipes. That's a separate and as yet unfinished PR but this is a bug with something I didn't touch and should be handled separately.

This probably wasn't caught earlier because as far as I can tell there _are_ no base GT recipes that have ranged outputs.

I'm working on a PR to fix this issue but I'm reporting it first.

### PR DESCRIPTION
**Pull request by DilithiumThoride**
## What
Fixes #3267 

## Implementation Details
Implements the several missing cases from outputItems(Object) and fixes a recursive call in inputItems(Object, int)

### CODE REVIEW

**Review by YoungOnionMC — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java [hunk 1]
```diff
@@ -541,6 +558,19 @@ public GTRecipeBuilder outputItems(Object input, int count) {
         }
     }
 
+    public GTRecipeBuilder outputItems(Ingredient output) {
+        return output(ItemRecipeCapability.CAP, output);
+    }
+
+    public GTRecipeBuilder outputItems(Ingredient output, int amount) {
+        Ingredient countedOutput = Ingredient.of(output.getItems());
+        return input(ItemRecipeCapability.CAP, countedOutput);
```
Comment (Ricky-fight) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:567]: why `input` instead of `outout`?

Comment (Spicierspace153) [reply src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:567]: hi this already got merged, thank you for your comment tho!

File: src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java [hunk 2]
```diff
@@ -386,6 +386,11 @@ public GTRecipeBuilder inputItems(Ingredient... inputs) {
         return input(ItemRecipeCapability.CAP, inputs);
     }
 
+    public GTRecipeBuilder inputItems(Ingredient inputs, int count) {
+        Ingredient countedInput = Ingredient.of(inputs.getItems());
+        return input(ItemRecipeCapability.CAP, countedInput);
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:391]: This doesn't actually set the count?
All it does is make the ingredient invalid if it's a tag.

File: src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java [hunk 3]
```diff
@@ -541,6 +558,19 @@ public GTRecipeBuilder outputItems(Object input, int count) {
         }
     }
 
+    public GTRecipeBuilder outputItems(Ingredient output) {
+        return output(ItemRecipeCapability.CAP, output);
+    }
+
+    public GTRecipeBuilder outputItems(Ingredient output, int amount) {
+        Ingredient countedOutput = Ingredient.of(output.getItems());
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:566]: Ditto

File: src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java [hunk 4]
```diff
@@ -541,6 +558,19 @@ public GTRecipeBuilder outputItems(Object input, int count) {
...
+        return input(ItemRecipeCapability.CAP, countedOutput);
+    }
+
+    public GTRecipeBuilder outputItems(IntProviderIngredient output) {
+        return output(ItemRecipeCapability.CAP, output);
+    }
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:572]: No need to add a special case for this, the normal Ingredient method handles it just fine.

File: src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java [hunk 5]
```diff
@@ -541,6 +558,19 @@ public GTRecipeBuilder outputItems(Object input, int count) {
         }
     }
 
+    public GTRecipeBuilder outputItems(Ingredient output) {
+        return output(ItemRecipeCapability.CAP, output);
+    }
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:563]: It shouldn't be suggested in any way that using `Ingredient`s for outputs is anything but a quirk of the way we handle inputs & outputs, so adding this method is bad API design.

File: src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java [hunk 6]
```diff
@@ -620,6 +650,17 @@ public GTRecipeBuilder outputItems(MachineDefinition machine, int count) {
...
+    public GTRecipeBuilder outputItems(TagKey<Item> tag, int amount) {
+        if (amount == 0) {
+            GTCEu.LOGGER.error("Item Count is 0, id: {}", id);
+        }
+        return outputItems(SizedIngredient.create(tag, amount));
+    }
+
+    public GTRecipeBuilder outputItems(TagKey<Item> tag) {
+        return outputItems(tag, 1);
+    }
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:662]: Tags are the reason `Ingredient` outputs aren't supported, as we have no idea which item you actually want from them and just pick the first item, which, most of the time, _is not the item the user actually wants to output._

File: src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java (hunk 2 above)
Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:391]: This should've done `return SizedIngredient.create(inputs, count);` instead.

**Review by screret — CHANGES_REQUESTED** [review]
Though the original issues *are* my fault, there is a reason you can't output a tag or Ingredient easily.
@YoungOnionMC please look at what a PR actually does before you merge it? This change has some unfortunate side-effects as it stands.
