### PR TITLE
Fix #1125

### LINKED ISSUE #1125: Parallel Control Hatch Bug
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.2.0.a-build_606

### Recipe Viewer Installed

None

### Environment

Singleplaye

### Cross-Mod Interaction

Yes

### Other Installed Mods

AE2 and so on

### Expected Behavior

.

### Actual Behavior

In a multi-block structure, when producing items with the same voltage as the machine, if the Parallel Control Hatch is set to more than 1, the machine will not operate properly.

### Steps to Reproduce

.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gjmhmm8**
[Fix #1125](https://github.com/GregTechCEu/GregTech-Modern/issues/1125)

### CODE REVIEW

**Review by TheAlaskanPhysicist — APPROVED** [review]
LGTM

File: src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java [hunk 1]
```diff
@@ -108,7 +108,8 @@ private static Tuple<GTRecipe, Integer> tryParallel(IRecipeCapabilityHolder hold
         int mid = (min + max) / 2;
 
         GTRecipe copied = original.copy(ContentModifier.multiplier(mid), modifyDuration);
-        if (!copied.matchRecipe(holder).isSuccess() || !copied.matchTickRecipe(holder).isSuccess()) {
+        if (!copied.matchRecipe(holder).isSuccess() || !copied.matchTickRecipe(holder).isSuccess() ||
+            !(RecipeHelper.getRecipeEUtTier(copied) <= ((ITieredMachine)holder).getTier())) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java]: can you be absolutely sure it'll always be a tiered machine?

Comment (gjmhmm8) [reply src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java]: Currently, those that can use the parallel control cabin are, but it’s better to add a judgment just in case.

File: src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java [hunk 2]
```diff
@@ -95,6 +95,7 @@ public static Tuple<GTRecipe, Integer> accurateParallel(MetaMachine machine, @No
         if (maxParallel == 1) {
             return new Tuple<>(recipe, 1);
         }
+        if(!(machine instanceof ITieredMachine))return new Tuple<>(recipe, 1);
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java]: what if someone makes a primitive machine with a parallel hatch for some reason? (as an example) it still has to go through.

**Review by screret — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java (hunk 2 above)
Comment (gjmhmm8) [reply src/main/java/com/gregtechceu/gtceu/common/data/GTRecipeModifiers.java:98]: What do you think should be done to solve it?

**Review by screret — APPROVED** [review]
