### PR TITLE
Jetpack Fixes

### LINKED ISSUE #1812: Jetpack uses energy whenever player is not touching ground
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.0

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

None

### Expected Behavior

Jetpack should not consume energy when you are not actively using it

### Actual Behavior

Jetpack consumes energy whenever you are not touching the ground like when falling, swimming, stuck in cobweb, sleeping in bed

### Steps to Reproduce

equip electric jetpack
enable engines
fall through cobwebs just don't stand on any block

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by krossgg**
## What
- Fixes incorrect jetpack flying behavior in `IJetpack` ( fixes #1812 )
- Fixes `onEntityLivingFallEvent` to actually cancel fall damage *only if* suit boots are worn, or to engage ehover if a jetpack is worn
- Modify jetpacks' `onArmorTick` so that NBT doesn't get overridden after an ehover

## Implementation Details
Note that the AdvancedJetpack armor tick logic is identical to the regular Jetpack, so it doesn't need to specifically be overridden

## Outcome
Jetpacks less jank

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/common/item/armor/AdvancedNanoMuscleSuite.java [hunk 1]
```diff
@@ -49,49 +49,49 @@ public void onArmorTick(Level world, Player player, @NotNull ItemStack item) {
...
+        byte toggleTimer = data.getByte("toggleTimer");
+        boolean canShare = data.getBoolean("canShare");
+
+        String messageKey = null;
+        if (toggleTimer == 0) {
+            if (KeyBind.JETPACK_ENABLE.isKeyDown(player)) {
+                jetpackEnabled = !jetpackEnabled;
+                messageKey = "metaarmor.jetpack.flight." + (jetpackEnabled ? "enable" : "disable");
+                data.putBoolean("enabled", jetpackEnabled);
+            } else if (KeyBind.ARMOR_HOVER.isKeyDown(player)) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/item/armor/AdvancedNanoMuscleSuite.java:71]: probably shouldn't be an `else if`.

File: src/main/java/com/gregtechceu/gtceu/common/item/armor/IJetpack.java [hunk 2]
```diff
@@ -70,97 +70,84 @@ default float getFallDamageReduction() {
...
-                        player.moveRelative(speedSideways * 0.8f, new Vec3(0, 0, -speedForward));
-                    }
-                    if (KeyBind.VANILLA_LEFT.isKeyDown(player)) {
-                        player.moveRelative(speedSideways, new Vec3(speedSideways, 0, 0));
-                    }
-                    if (KeyBind.VANILLA_RIGHT.isKeyDown(player)) {
-                        player.moveRelative(-speedSideways, new Vec3(speedSideways, 0, 0));
-                    }
+
+                if (player.isFallFlying()) { // if the player is hovering negate fall motion
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/item/armor/IJetpack.java:98]: isn't `isFallFlying` used for gliders? e.g. the elytra?

**Review by screret — CHANGES_REQUESTED** [review]

**Review by screret — APPROVED** [review]
