### PR TITLE
Changed Ingredient tree creation behavior

### LINKED ISSUE #1839: Steam Oven doesn't smelt ores
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

gtceu-1.20.1-1.4.0-build_1032-SNAPSHOT

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Modpack based on Sky Greg

### Expected Behavior

end coal ore and end iron ore should be smeltable like shown in the recipe viewer (both when looking up the steam oven, or the ore)

### Actual Behavior

putting in 1, 8 or 64 end iron/coal ore will not start the smelting process - the steam oven is formed, not on/over a chunk edge and the steam input hatch is full. iron ingots are smelted without issues into wrought iron.

these ores are smeltable in a vanilla furnace without issues and produce 2 ingots / 4 coal as shown in JEI/EMI.

NOTE: the iron ingot -> wrought iron is added by kubejs:
```event.smelting('gtceu:wrought_iron_ingot', 'minecraft:iron_ingot')```

### Steps to Reproduce

1. build steam oven
2. fill steam hatch
3. put end iron/coal ore into the input bus

### Additional Information

I looked at the code and it doesn't seem that it's related to a config option - but these are some config options which may be related:
disableManualCompression: true
harderBrickRecipes: true
nerfWoodCrafting: true
hardWoodRecipes: true
hardIronRecipes: true
hardRedstoneRecipes: true
hardToolArmorRecipes: true
hardMiscRecipes: true
hardGlassRecipes: true
nerfPaperCrafting: true
hardAdvancedIronRecipes: true
harderCharcoalRecipe: true
flintAndSteelRequireSteel: true
removeVanillaBlockRecipes: true
removeVanillaTNTRecipe: true

### PR DESCRIPTION
**Pull request by krossgg**
## What
While caching the ingredients for recipes and adding them to the recipe lookup map, IntersectionIngredients were split up into their constituent MapIngredients. This caused the recursive recipe lookup to be unable to find recipes that used an IntersectionIngredient. See [`GTRecipeLookup#recurseIngredientTreeFindRecipeCollisions`](https://github.com/GregTechCEu/GregTech-Modern/blob/1815527d7ca4785a9e91f5dad1c2ef96a8bbbb67/src/main/java/com/gregtechceu/gtceu/api/recipe/lookup/GTRecipeLookup.java#L189) for more details

Now, it no longer splits Intersection Ingredients
Fixes #1839 

## Outcome
Oin happy 😄

### CODE REVIEW

**Review by screret — APPROVED** [review]
wait does this just work?

File: src/main/java/com/gregtechceu/gtceu/api/recipe/lookup/GTRecipeLookup.java [hunk 1]
```diff
@@ -373,15 +372,6 @@ protected static void retrieveCachedIngredient(@NotNull List<List<AbstractMapIng
...
-            if (mappedIngredient instanceof MapIntersectionIngredient intersection) {
-                for (Ingredient inner : intersection.ingredients) {
-                    List<AbstractMapIngredient> converted = ItemRecipeCapability.CAP.convertToMapIngredient(inner);
-                    retrieveCachedIngredient(list, converted, cache);
-                }
-                added = true;
-            }
         }
         if (!added) {
             list.add(ingredients);
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/recipe/lookup/GTRecipeLookup.java]: you could also remove the `!added` check from here, and the `added` field itself

**Review by screret — APPROVED** [review]
