### PR TITLE
Fix data stick not copying distinct bus from me input bus

### LINKED ISSUE #2344: Data Stick does not copy all settings of ME (Stocking) Input Bus
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.5.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Applied Energistics, Jade, EMI

### Expected Behavior

Data stick should copy all settings

### Actual Behavior

Data stick does not copy Distinct mode

### Steps to Reproduce

Data stick copies seemingly everything but distinct mode on input bus.

### Additional Information

Happens on both ME Input Bus and ME Stocking Input Bus

### PR DESCRIPTION
**Pull request by omergunr100**
## What
Adds the distinct bus field to the copied and pasted nbt.

## Suggestion
I suggest unifying the configuration copy pasting to a single interface that lets you:
1. Copy machine configuration as nbt.
2. Paste machine configuration as nbt.
3. Get what tools/items are allowed to copy/paste this machine configuration (if we want to keep this behaviour on the data stick)

(personal opinion warning)
I think the data stick interaction is a bit weird, we have a way of doing exactly that with item behaviours. (also see #2405 )
also copying on left click feels a bit clunky to me, I feel like copying on `shift + <copy key>` feels better but that's just me.

## Also
Fixes #2344

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEInputBusPartMachine.java [hunk 1]
```diff
@@ -188,6 +188,7 @@ protected CompoundTag writeConfigToTag() {
         }
         tag.putByte("GhostCircuit",
                 (byte) IntCircuitBehaviour.getCircuitConfiguration(circuitInventory.getStackInSlot(0)));
+        tag.putBoolean("DistinctBusses", isDistinct());
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEInputBusPartMachine.java]: it's "Buses" with 1 `s`

File: src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEInputBusPartMachine.java [hunk 2]
```diff
@@ -207,5 +208,8 @@ protected void readConfigFromTag(CompoundTag tag) {
         if (tag.contains("GhostCircuit")) {
             circuitInventory.setStackInSlot(0, IntCircuitBehaviour.stack(tag.getByte("GhostCircuit")));
         }
+        if (tag.contains("DistinctBusses")) {
+            setDistinct(tag.getBoolean("DistinctBusses"));
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEInputBusPartMachine.java]: it's "Buses" with 1 `s`

**Review by screret — DISMISSED** [review]

**Review by YoungOnionMC — APPROVED** [review]

**Review by screret — APPROVED** [review]
