### PR TITLE
ME Bus & Hatch Rework

### LINKED ISSUE #1281: ME Buses and Hatches are not functioning correctly
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.2.2.a-build_688

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

AE2

### Expected Behavior

Place and connect the buses and hatches to a network with sufficient channels, expected it to function normally.

### Actual Behavior

The output bus and hatch are sometimes offline, and sometimes the recipe cannot start, or the output buses and hatches voids items and fluids. The me input buses and hatches are also voiding fluids when the recipe starts (i.e. the recipe starts but there is no produsts), or the recipes cannot start when providing with enough ingredients in it.

### Steps to Reproduce

As I mentioned above.

### Additional Information

The network logic itself is very buggy, sometimes the cable cannot even connect the buses and hatches, especially after rotating using a wrench.

### LINKED ISSUE #1306: [Bug] A detailed List of Bugs of ME Parts
As I mentioned in #1281, the ME Parts cannot function normally. Here is a detailed list of those incorrect behaviours:

1. ME Input Bus and Input Hatch: Sometimes voids ingredients, will make the machine start but no final products is produced, and the amount of consumed material is not consistant with the recipe.
(As far as I remember both buses have the same issue like this, however I cannot reproduce it with the ME Input Bus, so I am not sure, but it is obvious that the ME Input Hatch has this issue.)

2. ME Output Bus often voids items, it seems like when the items stored in the bus is higher than 16 stack, machine cannot add more item into the ME Output Bus, so the item get voided.

3. ME Output Hatch will not be considered as a valid Output Hatch, that is, it will not make the machine start working when there is a fluid output, and no fluid will be stored in the hatch, when other fluid hatches are presented.

4. ME Output Bus and Output Hatch displays as offline when connected to a ME system, the ME Output Bus will became normal when it has content in it, however I don't know if that's the case for ME Output Hatch since I said it is not considered as a valid output hatch. Also, when using a wrench to rotate the bus/hatch, the AE cable cannot be notified and connect to the bus/hatch. You have to break and place it again with right direction the first time.

5. The items in the ME Output Bus often cannot render, but when you point at it, the name will be displayed.

6. When ME Output Bus is updating (with the network, right click and open its GUI may cause game to crash)

### LINKED ISSUE #1382: Server Crash ( Aluminium Drum + ME Stocking Input Bus )
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.2.3.a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

ImmersiveEngineering-1.20.1-10.1.0-171, appliedenergistics2-forge-15.0.23

### Expected Behavior

Aluminium Drum in Config Slot ME Stocking Input Bus will not cause a crash

### Actual Behavior

Aluminium Drum in Config Slot ME Stocking Input Bus causes a crash server

### Steps to Reproduce

1) Open ME Stocking Input Bus
2) Place Aluminium Drum in Config Slot ( repeatedly )
3) Server Crash

### Additional Information

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-06-06 21:32:46
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void com.gregtechceu.gtceu.integration.ae2.util.AmountSetSlot.writeClientAction(int, java.util.function.Consumer)'
	at com.gregtechceu.gtceu.integration.ae2.util.AmountSetSlot.setSlotIndex(AmountSetSlot.java:42) ~[gtceu-1.20.1-1.2.3.a.jar%23269!/:?] {re:classloading}
	at com.gregtechceu.gtceu.integration.ae2.gui.widget.AEConfigWidget.disableAmount(AEConfigWidget.java:42) ~[gtceu-1.20.1-1.2.3.a.jar%23269!/:?] {re:classloading}
	at com.gregtechceu.gtceu.integration.ae2.util.AEItemConfigSlot.handleClientAction(AEItemConfigSlot.java:125) ~[gtceu-1.20.1-1.2.3.a.jar%23269!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.handleClientAction(WidgetGroup.java:620) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.handleClientAction(WidgetGroup.java:620) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.handleClientAction(WidgetGroup.java:620) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.handleClientAction(WidgetGroup.java:620) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.lowdragmc.lowdraglib.gui.widget.WidgetGroup.handleClientAction(WidgetGroup.java:620) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.lowdragmc.lowdraglib.gui.modular.ModularUIContainer.handleClientAction(ModularUIContainer.java:273) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.networking.c2s.CPacketUIClientAction.execute(CPacketUIClientAction.java:46) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.networking.forge.Networking.lambda$register$2(Networking.java:51) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:212) ~[forge-1.20.1-47.2.30-universal.jar%23303!/:?] {re:classloading}
	at com.lowdragmc.lowdraglib.networking.forge.Networking.lambda$register$3(Networking.java:51) ~[ldlib-forge-1.20.1-1.0.25.j.jar%23323!/:?] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:115) ~[forge-1.20.1-47.2.30-universal.jar%23303!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	at net.minecraftforge.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:115) ~[forge-1.20.1-47.2.30-universal.jar%23303!/:?] {re:classloading}
	at net.minecraftforge.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:153) ~[forge-1.20.1-47.2.30-universal.jar%23303!/:?] {re:classloading}
	at net.minecraftforge.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:63) ~[forge-1.20.1-47.2.30-universal.jar%23303!/:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:263) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:255) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23149!/:?] {}
	at net.minecraftforge.network.NetworkInstance.dispatch(NetworkInstance.java:68) ~[forge-1.20.1-47.2.30-universal.jar%23303!/:?] {re:classloading}
	at net.minecraftforge.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:84) ~[forge-1.20.1-47.2.30-universal.jar%23303!/:?] {re:classloading}
	at java.util.Optional.map(Optional.java:260) ~[?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
	at net.minecraftforge.network.NetworkHooks.onCustomPayload(NetworkHooks.java:84) ~[forge-1.20.1-47.2.30-universal.jar%23303!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_7423_(ServerGamePacketListenerImpl.java:2846) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:gtceu.mixins.json:ServerGamePacketListenerImplAccessor,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:35) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.m_5797_(ServerboundCustomPayloadPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:computing_frames,re:mixin,re:classloading,re:mixin}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1027) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:173) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1010) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1004) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:989) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:906) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23298!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}

### LINKED ISSUE #1529: Server crash with AE integration
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.3.0a

### Recipe Viewer Installed

JEI

### Environment

Dedicated Server.

### Cross-Mod Interaction

No

### Other Installed Mods

The crash log contains all the information - https://paste.fuix.net/amdRZkG

### Expected Behavior

The crash log contains all the information - https://paste.fuix.net/amdRZkG

### Actual Behavior

The crash log contains all the information - https://paste.fuix.net/amdRZkG

### Steps to Reproduce

image
In an attempt to configure the gtceu:me_input_hatch, the server crashes (When you enter the text)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gateguardian523**
## What
Refactor and fix the ME Hatch&Bus of GTM, merging ME Hatch&Bus from Gregic Energistics.

## Goals
- [x] Preparation. Merge some of the tool methods from Monomorphism
- [x] Refactor and fix the ME Hatch&Bus of GTM
- [x] Merge ME Hatch&Bus from Gregic Energistics

## Outcomes
Fixes #1281
Fixes #1306
Fixes #1382
Fixes #1529

### CODE REVIEW

**Comment by screret** [comment]
when's this going to be completed?

**Comment by gateguardian523** [comment]
It will take no more than a week

**Comment by screret** [comment]
👍

**Comment by screret** [comment]
status?

**Comment by gateguardian523** [comment]
Almost finished

File: src/main/java/com/gregtechceu/gtceu/api/machine/feature/IDataStickIntractable.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+import net.minecraft.core.Direction;
+import net.minecraft.world.InteractionHand;
+import net.minecraft.world.InteractionResult;
+import net.minecraft.world.entity.player.Player;
+import net.minecraft.world.item.ItemStack;
+import net.minecraft.world.level.Level;
+import net.minecraft.world.level.block.state.BlockState;
+import net.minecraft.world.phys.BlockHitResult;
+
+public interface IDataStickIntractable extends IInteractedMachine {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/machine/feature/IDataStickIntractable.java]: typo: should be `IDataStickInteractable`

**Comment by screret** [comment]
is this complete now?

**Comment by gateguardian523** [comment]
The feature is complete, but I'm still testing for potential bugs

**Comment by screret** [comment]
👍 could you update the branch so we can get a test build out?

**Comment by screret** [comment]
also mark it as ready for review

**Comment by gateguardian523** [comment]
OK

File: src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java [hunk 2]
```diff
@@ -0,0 +1,330 @@
...
+                    var key = config.what();
+                    long result = aeNetwork.extract(key, Long.MAX_VALUE, Actionable.SIMULATE, actionSource);
+                    slot.setStock(new GenericStack(key, result));
+                    slot.onContentsChanged();
+                }
+            }
+            this.updateTankSubscription();
+        }
+
+        if (!autoPull || !(getOffsetTimer() % 100 == 0)) return;
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java:120]: the config has a value named `updateIntervals` for how often the ME parts should update. use that instead of a hardcoded value?

File: src/main/java/com/gregtechceu/gtceu/integration/ae2/slot/ExportOnlyAEFluidList.java [hunk 3]
```diff
@@ -0,0 +1,187 @@
...
+    }
+
+    @Override
+    public FluidStorage[] getStorages() {
+        if (this.fluidStorages == null) {
+            this.fluidStorages = Arrays.stream(this.inventory)
+                    .map(FluidStorageDelegate::new).toArray(FluidStorage[]::new);
+            return this.fluidStorages;
+        } else {
+            return this.fluidStorages;
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/integration/ae2/slot/ExportOnlyAEFluidList.java]: you can remove the else branch and just always return `this.fluidStorages`

**Review by screret — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java (hunk 2 above)
Comment (gate-guardian) [reply src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java:120]: This is a separate value in MEStocking, used to represent the interval time for automatic pulling.

In NH, there is a PR that allows this value to be modified in GUI, but in CEU, this value is hard coded to 5 seconds

Comment (gate-guardian) [reply src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java:120]: I can add interval time and minimum pull settings like NH, but I don't know how to design GUI

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java:120]: I see. that's fine, then.

Comment (gate-guardian) [reply src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java:120]: I am unable to perform hot swap in the GTM development environment (Unexpected: JDWP Error: 113). This has turned GUI writing into a disaster.

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java:120]: yep, same, it seems that architectury really hates hotswapping, since on 1.21 it works perfectly.

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java:120]: let's just leave it as is for now.

Comment (gate-guardian) [reply src/main/java/com/gregtechceu/gtceu/integration/ae2/machine/MEStockingHatchPartMachine.java:120]: i hate arch loom :(

**Review by screret — APPROVED** [review]
