### PR TITLE
Fix a bunch of visual bugs

### LINKED ISSUE #1569: Rendering issue with material blocks
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.20.1-1.3.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

No other mods.

### Expected Behavior

Block outline when the block is looked at should be opaque like every other block.

### Actual Behavior

Block outline is transparent and shows the skybox through it.

### Steps to Reproduce

Look at any GT material blocks (Aluminium Block, Flint Block, etc.). You should be able to notice that you can see the skybox through it.

### Additional Information

_No response_

### LINKED ISSUE #2254: Glitching on some controllers and hatches with covers when using Gregtech Revival texture pack
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer 

### Cross-Mod Interaction

Unsure

### Other Installed Mods

No additional mods. Just GregTech Revival 32x 1.19.2-1.20.1-1.21 ver 0.16 Resource Pack.

### Expected Behavior

No glitchning

### Actual Behavior

Applying a texture pack should not cause the glitching...

### Steps to Reproduce

Install 1.20.1 instance
Add GTCEu Modern 1.4.6
Create a LCR
Add a hatch and apply a cover

In the main game (Monifactory) when using an emitter on the controller the glitching also occurs.

### Additional Information

I've reported the issue to the Resource pack developer [here](https://github.com/ilaores/GregtechRevival32x/issues/3) 

Video:

https://github.com/user-attachments/assets/836f4fb4-367a-4a89-a69b-2a15db8a2bc2

The glitching only seems to happen with GT Revival and mostly seems to affect the LCR. I haven't observed issues elsewhere, yet. 

This also seems to be quite recent. However, I'd need to check earlier saves/releases to see when this started happening

### PR DESCRIPTION
**Pull request by omergunr100**
## What
Cover overlays no longer z-fight with other overlays.
Multiblock parts no longer z-fight in preview.
The tape overlay renders above the maintenance hatch overlay.
Material block highlights are the base colour instead of translucent*.
Red selection overlay in multiblock preview no longer z-fights with other overlays.

## Implementation Details
Material block highlights are now a cancelling mixin.
Material block highlights also "fix" surrounding blocks, when you highlight a block that has an immediate neighbor which is a material block it'll render it's own highlight with full opacity to not make the material block invisible.
Material blocks will still render invisible through highlights of block which aren't their immediate neighbors but that's less noticeable, so I think it's an improvement overall. 🤷‍♂️ 

Everything else about this is questionable too, but like who cares?

## Resolves
Resolves #1569
Resolves #2254
Fixes an assortment of hardware specific bugs introduced by yours truly in #2823.
Fixes boiler renderer rendering parts based on the part orientation instead of the controller orientation.

## Potential Compatibility Issues
Changed the block highlight mixin to be cancelling.
Other multiblock renderers might need to adjust their overlay offset to adjust to the new offsets. (some of ours might need this too, this really needs some play-testing or another review of all our overlay renderers)

### CODE REVIEW

**Review by screret — APPROVED** [review]

**Review by screret — APPROVED** [review]

**Review by YoungOnionMC — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/data/machines/GTMachineUtils.java [hunk 1]
```diff
@@ -478,7 +478,7 @@ public static MultiblockMachineDefinition registerLargeBoiler(String name, Suppl
                 .multiblock("%s_large_boiler".formatted(name),
                         holder -> new LargeBoilerMachine(holder, maxTemperature, heatSpeed))
                 .langValue("Large %s Boiler".formatted(FormattingUtil.toEnglishName(name)))
-                .rotationState(RotationState.ALL)
+                .rotationState(RotationState.NON_Y_AXIS)
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/data/machines/GTMachineUtils.java:483]: this needs to also do `.allowExtendedFacing(false)`

**Review by screret — DISMISSED** [review]

**Review by Ghostipedia — APPROVED** [review]
