### PR TITLE
fix JEI compatibility

### LINKED ISSUE #1660: [Crash]: java.util.ServiceConfigurationError
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

v1.3.1

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Startup

### Cross-Mod Interaction

Yes

### Other Installed Mods

Just Enough Items in the "Infinite Horizons - Modded Superflat Survival" modpack in which I am authoring.

### Expected Behavior

For the game to launch without crashing.

### Actual Behavior

Game crashes upon startup.

### Steps to Reproduce

Launch the game.

### Additional Information

I was forwarded here from the JEI Github page attached here:  https://github.com/mezz/JustEnoughItems/issues/3667

### PR DESCRIPTION
**Pull request by screret**

### CODE REVIEW

**Review by Ghostipedia — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/core/mixins/jei/FluidHelperMixin.java [hunk 1]
```diff
@@ -2,25 +2,24 @@
...
 public class FluidHelperMixin {
 
-    @Inject(method = "getTooltip*", at = @At("TAIL"), remap = false)
-    private void gtceu$injectFluidTooltips(FluidStack ingredient, TooltipFlag tooltipFlag,
-                                           CallbackInfoReturnable<List<Component>> cir) {
-        var tooltip = cir.getReturnValue();
-        TooltipsHandler.appendFluidTooltips(ingredient.getFluid(), ingredient.getAmount(), tooltip, tooltipFlag);
+    @Inject(method = "getTooltip(Lmezz/jei/api/gui/builder/ITooltipBuilder;Lnet/minecraftforge/fluids/FluidStack;Lnet/minecraft/world/item/TooltipFlag;)V",
+            at = @At("TAIL"),
+            remap = false)
```
Comment (mezz) [inline src/main/java/com/gregtechceu/gtceu/core/mixins/jei/FluidHelperMixin.java:20]: @screret could you add a `require = 0` to the inject here so that if it fails to find the injection site, it fails without crashing?
Losing the ability to add info to the tooltip when JEI updates seems better than crashing, imo.
