### PR TITLE
Increase density of Realgar in Copper/Tin Veins

### LINKED ISSUE #2212: Realgar density very low in Copper Tin Veins
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.6

### Minecraft Version

1.20.1

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

N/a

### Expected Behavior

Higher Realgar density. This is shown with the vein builder's rareBlockChance increased to 0.15 and gives 2-4 stacks per vein.
Screenshot_2024-10-18_021935

### Actual Behavior

Realgar density is extremely low in Copper Tin veins - the first vein I found had 54 Realgar.

### Steps to Reproduce

1. Load up a new world with GTM
2. Find a Realgar Vein
3. Oh it def shouldn't be _that_ low, oops

### Additional Information

I'm putting this on the issue tracker as a reminder, since it's already [confirmed to be unintentional by Screret](https://discord.com/channels/701354865217110096/1089296351906504835/1296723783385874464)

### PR DESCRIPTION
**Pull request by Spicierspace153**
adds more realgar in coppertin veins
closes #2212

### CODE REVIEW

**Comment by Spicierspace153** [comment]
fixes issue #2212

**Review by YoungOnionMC — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/common/data/GTOres.java [hunk 1]
```diff
@@ -406,7 +406,7 @@ public class GTOres {
                     .oreBlock(new VeinBlockDefinition(Chalcopyrite, 5))
                     .oreBlock(new VeinBlockDefinition(Zeolite, 2))
                     .oreBlock(new VeinBlockDefinition(Cassiterite, 2))
-                    .rareBlock(new VeinBlockDefinition(Realgar, 1))
+                    .rareBlock(new VeinBlockDefinition(Realgar, 2))
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/data/GTOres.java]: this change does literally nothing as there's only 1 rare block. increase `rareBlockChance` instead

**Review by screret — DISMISSED** [review]

**Review by YoungOnionMC — APPROVED** [review]
