### PR TITLE
Jade battery provider

### LINKED ISSUE #4305: Turbo Charger Jade Info
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.4.0, 7.4.1 SNAPSHOT

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

I am playing on the standard community pack

### Expected Behavior

The turbo charger should display its energy usage, contained items, etc.

Maybe it could also display a time till items are charged.

### Actual Behavior

The turbo charger only displays its contained energy, nothing else.

### Steps to Reproduce

Nothing special. Just charge any item in a turbo charger.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by zetrock1**
## What
Resolve  #4305

## Outcome
Add jade support for batteries in batteryBuffer and ChargerMachine

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java [hunk 1]
```diff
@@ -0,0 +1,122 @@
...
+    public void appendTooltip(ITooltip iTooltip, BlockAccessor blockAccessor, IPluginConfig iPluginConfig) {
+        if (blockAccessor.getBlockEntity() instanceof IMachineBlockEntity blockEntity) {
+            if (blockEntity.getMetaMachine() instanceof ChargerMachine ||
+                    blockEntity.getMetaMachine() instanceof BatteryBufferMachine) {
+                CompoundTag serverData = blockAccessor.getServerData();
+                if (serverData.contains("batteries")) {
+                    CompoundTag tag = serverData.getCompound("batteries");
+                    long changed = tag.getLong("changed"), stored = tag.getLong("stored"),
+                            capacity = tag.getLong("capacity");
+                    iTooltip.add(Component.literal("EU/sec: " + changed));
```
Comment (Reabstraction) [inline src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java]: This should be made translatable

File: src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java [hunk 2]
```diff
@@ -0,0 +1,122 @@
...
+                    if (changed > 0) {
+                        iTooltip.add(Component
+                                .literal("Until fully charged: " + getStringRemainTime((capacity - stored) / changed)));
```
Comment (Reabstraction) [inline src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java]: This also should be made translatable

File: src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+                    } else if (changed < 0) {
+                        iTooltip.add(Component.literal("Until empty " + getStringRemainTime(stored / -changed)));
```
Comment (Reabstraction) [inline src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java]: This also should be made translatable

File: src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java [hunk 4]
```diff
@@ -0,0 +1,122 @@
...
+                    }
+                    if (Minecraft.getInstance().player.isShiftKeyDown()) {
+                        CustomItemStackHandler handler = new CustomItemStackHandler();
+                        handler.deserializeNBT(tag.getCompound("storage"));
+                        IElementHelper helper = iTooltip.getElementHelper();
+                        for (int i = 0; i < handler.getSlots(); i++) {
+                            if (handler.getStackInSlot(i).getCount() != 0) {
+                                ItemStack stack = handler.getStackInSlot(i);
+                                iTooltip.add(helper.smallItem(stack));
+                                IElectricItem item = GTCapabilityHelper.getElectricItem(stack);
```
Comment (Reabstraction) [inline src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java:59]: Add explicit handling for the case that the item somehow isn't an electric item

**Review by Reabstraction — DISMISSED** [review]

**Comment by zetrock1** [comment]
image
image
image

File: src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+                CompoundTag tag = new CompoundTag();
+                IEnergyContainer container = machine.energyContainer;
+                tag.putLong("changed", container.getInputPerSec() - container.getOutputPerSec());
+                tag.putLong("capacity", container.getEnergyCapacity());
+                tag.putLong("stored", container.getEnergyStored());
+                tag.put("storage", machine.getBatteryInventory().serializeNBT());
+                compoundTag.put("batteries", tag);
+            }
+        }
+    }
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java:96]: Since this code does the same thing, can this be simplified? 
like would
```
IEnergyContainer container = null;
if(machine instanceof ChargerMachine machine){
    container = machine.energyContainer;
} else if( machine instanceof BatteryBufferMachine machine){
    container = machine.energyContainer;
} else {
    return;
}
[rest of the code]
```

**Review by jurrejelle — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java [hunk 6]
```diff
@@ -0,0 +1,129 @@
...
+                                                " / " + formatEnergy(item.getMaxCharge(), 100000) + " EU"));
+                            }
+                        }
+                    }
+                }
+            }
+        }
+    }
+
+    private String getStringRemainTime(long time) {
```
Comment (Spicierspace153) [inline src/main/java/com/gregtechceu/gtceu/integration/jade/provider/BatteryStorageInfoProvider.java]: maybe move this to gt utils? seems useful in other cases as well

**Review by TarLaboratories — APPROVED** [review]
LGTM

**Review by jurrejelle — APPROVED** [review]
