### PR TITLE
Fix maintenance not happening as often as intended

### LINKED ISSUE #998: Maintenance Frequency
### Cross-mod Integration

_No response_

### Feature Description

I feel like I have never had to do maintenance on my multiblocks in GTCEU Modern outside of the initial construction. And that just doesn't feel right to me, I would like there to be a config option that increases or decreases the frequency of maintenance issues for multiblocks. By having it be a config option, that allows for it to be tuned to the player's or packdev's choice of how big of an issue it will be in one's playthrough.

### PR DESCRIPTION
**Pull request by serenibyss**
Incorporates the fixes from https://github.com/GregTechCEu/GregTech/pull/1894

Closes https://github.com/GregTechCEu/GregTech-Modern/issues/998

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/config/ConfigHolder.java [hunk 1]
```diff
@@ -460,11 +460,6 @@ public static class MachineConfigs {
         @Configurable
         @Configurable.Comment({ "Whether to enable the Maintenance Hatch, required for Multiblocks.", "Default: true" })
         public boolean enableMaintenance = true;
-        @Configurable
-        @Configurable.Comment({
-                "Time in ticks between when Multiblocks can require Maintenance. By default, 48 hours.",
-                "Default: 3456000" })
-        public int maintenanceTime = 3456000;
```
Comment (gustovafing) [inline src/main/java/com/gregtechceu/gtceu/config/ConfigHolder.java:492]: Add the config option back

File: src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IMaintenanceMachine.java [hunk 2]
```diff
@@ -103,14 +89,23 @@ default void calculateMaintenance(IMaintenanceMachine maintenanceMachine, int du
             return;
         }
 
-        if (calculateTime((int) (duration * maintenanceMachine.getTimeMultiplier()))) {
-            if (GTValues.RNG.nextFloat() - 0.75f >= 0) {
+        setTimeActive(getTimeActive() + duration);
+        if (getTimeActive() >= 1000 / maintenanceMachine.getTimeMultiplier()) {
```
Comment (gustovafing) [inline src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IMaintenanceMachine.java]: Take `ConfigHolder.INSTANCE.machines.maintenanceTime` into account.

**Review by gustovafing — DISMISSED** [review]

File: src/main/java/com/gregtechceu/gtceu/config/ConfigHolder.java [hunk 3]
```diff
@@ -462,9 +462,10 @@ public static class MachineConfigs {
         public boolean enableMaintenance = true;
         @Configurable
         @Configurable.Comment({
-                "Time in ticks between when Multiblocks can require Maintenance. By default, 48 hours.",
-                "Default: 3456000" })
-        public int maintenanceTime = 3456000;
+                "How often to check for maintenance, rolling a 1/6000 chance every X ticks (before secondary effects like Configurable Maintenance Hatch).",
+                "In default settings, this equates to a 5% chance every hour of a machine running.",
+                "Default: 1000 (ticks)" })
+        public int maintenanceCheckRate = 1000;
```
Comment (serenibyss) [inline src/main/java/com/gregtechceu/gtceu/config/ConfigHolder.java:493]: I purposefully renamed this since:
1. It serves a very different purpose mathematically compared to before
2. The old default value of this config would lead to an even less likely chance of maintenance occurring than before with the old math

**Review by Ghostipedia — APPROVED** [review]
