### PR TITLE
Fix more decomp related issues

### LINKED ISSUE #3365: Decomp issues
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.0 snapshot

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

EMI

### Expected Behavior

The following blocks to have decomp recipes, and the ones with incorrect to have the correct one.

### Actual Behavior

The following blocks are missing decomp:
-Hatches/Buses (which causes bad decomp for quad/nonuple hatches)
-Empty Battery Capacitors (the shells not the actual batteries)
-Luv+ Energy/Dynamo Hatches (normal hatches, 4a, 16a and 64a have)
-me buses/hatches, pattern & proxy

The following blocks have their decomp wrong:
-Fusion glass (should be 16 beryllium, 2 Naqudah, 2 Ruridit and 8 tungsten Carbide)

Image

-All 4A, 16A and 64A energy/Dynamo hatches seem to have some issues on decomp recipes. For this example i will use IV energy hatches.
IV 4A decomp
Actual:
Image

Expected decomp: 10 TungstenSteel, 5 Tungsten, 2 Iridium, 2 Platinum (crafting tree for reference
Image

IV 16A decomp 
Actual:
Image

Expected decomp: 22 TungstenSteel, 13 Tungsten, 4 Platinum, 2 Iridium
Image

IV 64A decomp 
Actual:
Image

Expected decomp((USING TABLE RECIPE FOR TRANSFORMER)): 36 TungstenSteel, 37 Platinum, 29 Tungsten, 8.5 Niobium Titanium
Image

Expected decomp (USING ASSEMBLER RECIPE): 36 TungstenSteel, 29 Tungste, 21.5 Platinum, 7.5 Niobium Titanium
Image

-Power Transformer (IV example)
decomp/cost of assembler recipe: 18 Platinum, 8 TungstenSteel, 7 NiobiumTitanium, 41 nugget
Image

decomp/cost of table recipe: 33 Platinum, 8 TungstenSteel, 8 NiobiumTitanium
Image

actual decomp(seems to be a merge of both)
Image

### Steps to Reproduce

check emi

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by YoungOnionMC**
## What
turns out you need to recursively check stuff in the map when resolving the information
fixes #3365
for real this time

## Implementation Details
stripping out and cleaning up the resolve method and making it recursive to find every material

## Outcome
more correct decomp

## Additional Information
in #3365, the reason that power transformers are broken is because there are 2 separate recipes

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java [hunk 1]
```diff
@@ -173,29 +173,43 @@ public static void reinitializeMaterialData() {
...
+                    for (var matStack : singularMatInfo.getMaterials()) {
+                        stackList.add(matStack.multiply(inputCount).divide(outputCount));
+                    }
+                    if (info == null) { // if the info isn't set initialize it
+                        info = new ItemMaterialInfo(stackList);
+                        ITEM_MATERIAL_INFO.put(stack.getItem(), info);
+                    } else { // otherwise, add to it
+                        info.addMaterialStacks(stackList);
+                    }
+                }
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java:210]: Maybe add an else block here that logs a warning?
since an item not being in UNRESOLVED_ITEM_MATERIAL_INFO and also not having a getMaterialInfo(stack) now gets quietly ignored, but that should never happen I think

**Review by jurrejelle — COMMENTED** [review]
Cautious review, after the change it LGTM but there might be something obvious I'm missing. Might re-review when I'm more awake

File: src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java (hunk 1 above)
Comment (YoungOnionMC) [reply src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java:210]: no warning is needed, it still needs to add the item to the recipe, it just wont contribute anything to decomp

**Review by jurrejelle — APPROVED** [review]

File: src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java [hunk 2]
```diff
@@ -173,29 +173,43 @@ public static void reinitializeMaterialData() {
...
-            for (var input : entry.getValue()) {
-                var matStack = getMaterialInfo(input.getItem());
-                int inputCount = input.getCount();
-                if (matStack != null) {
-                    matStack.getMaterials()
-                            .forEach(ms -> stacks.add(ms.multiply(inputCount).divide(outputCount)));
-                }
+            var existingMaterialInfo = ITEM_MATERIAL_INFO.get(stack.getItem());
+            recurseFindMaterialInfo(existingMaterialInfo, stack);
+            if (existingMaterialInfo != null) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/data/chemical/material/ItemMaterialData.java:180]: shouldn't this query the info again in case `recurseFindMaterialInfo` initialized it?

File: src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java [hunk 3]
```diff
@@ -370,14 +370,19 @@ public GTRecipeBuilder inputItems(ItemStack input) {
...
+                    tempItemStacks.add(input);
+                }
                 if (matInfo != null) {
                     for (var matStack : matInfo.getMaterials()) {
                         tempItemMaterialStacks.add(matStack.multiply(input.getCount()));
                     }
-                } else {
+                } else if (unresolvedMatInfo == null) {
                     tempItemStacks.add(input);
                 }
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/data/recipe/builder/GTRecipeBuilder.java:384]: doesn't this always add the stack to `tempItemStacks`?
it adds it if `unresolvedMatInfo != null` and if `matInfo == null && unresolvedMatInfo == null`, and `matInfo` would always be null if the unresolved info is null, no?

**Review by screret — CHANGES_REQUESTED** [review]

**Review by screret — APPROVED** [review]

**Review by Spicierspace153 — APPROVED** [review]
