### PR TITLE
extended multi rotation

### LINKED ISSUE #380: Block changes direction when connecting directly to same other block???
### GregTech CEu Version

176

### Recipe Viewer Installed

JEI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Expected Behavior

No rotation of block????????

### Actual Behavior

So I placed two or more of the same combustion generator next to each other and the top texture rotated on its own but the function is no different. I don't know if this is something that COULD cause issues in the future or not, but just figured it was strange. If I place two of different tier combustion generators together, it will not do that. 

### Steps to Reproduce

Place generators next to each other, then apart. See difference. 

### Additional Information

I don't think this is a severe issue but I hope it can not lead to other issues later down so I feel maybe investigate?

### PR DESCRIPTION
**Pull request by screret**
it work yipppeeee
fixes #380

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/machine/multiblock/MultiblockControllerMachine.java [hunk 1]
```diff
@@ -204,4 +218,78 @@ public void onRotated(Direction oldFacing, Direction newFacing) {
...
+        if (blockState.getBlock() instanceof MetaMachineBlock metaMachineBlock &&
+                blockState.getValue(IMachineBlock.UPWARDS_FACING_PROPERTY) != upwardsFacing) {
+            getLevel().setBlockAndUpdate(getPos(),
+                    blockState.setValue(IMachineBlock.UPWARDS_FACING_PROPERTY, upwardsFacing));
+            if (getLevel() != null && !getLevel().isClientSide) {
+                notifyBlockUpdate();
+                markDirty();
+                checkPattern();
+            }
+        }
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/api/machine/multiblock/MultiblockControllerMachine.java:256]: I'd suggest early returns here to make it a bit more readable with the long-ish conditions.

Something like this maybe... (please double check before applying lol)

```suggestion
        if (!(blockState.getBlock() instanceof MetaMachineBlock metaMachineBlock)) return;
        if (blockState.getValue(IMachineBlock.UPWARDS_FACING_PROPERTY) == upwardsFacing) return;
            
        getLevel().setBlockAndUpdate(
                getPos(),
                blockState.setValue(IMachineBlock.UPWARDS_FACING_PROPERTY, upwardsFacing)
        );
        
        if (getLevel() != null && !getLevel().isClientSide) {
            notifyBlockUpdate();
            markDirty();
            checkPattern();
        }
```

File: src/main/java/com/gregtechceu/gtceu/client/renderer/machine/HPCAPartRenderer.java [hunk 2]
```diff
@@ -94,21 +94,25 @@ public void renderMachine(List<BakedQuad> quads, MachineDefinition definition, @
...
             }
         } else {
             ResourceLocation texture = this.texture;
             if (texture != null) {
-                quads.add(FaceQuad.bakeFace(FaceQuad.BLOCK, Direction.NORTH, ModelFactory.getBlockSprite(texture),
-                        modelState, -1, 0, true, true));
+                quads.add(
+                        StaticFaceBakery.bakeFace(StaticFaceBakery.SLIGHTLY_OVER_BLOCK, Direction.NORTH,
+                                ModelFactory.getBlockSprite(texture), modelState, -1, 0, true,
+                                true));
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/client/renderer/machine/HPCAPartRenderer.java]:
```suggestion
                quads.add(StaticFaceBakery.bakeFace(
                        StaticFaceBakery.SLIGHTLY_OVER_BLOCK, Direction.NORTH,
                        ModelFactory.getBlockSprite(texture), modelState, -1, 0, true, true
                ));
```

File: src/main/java/com/gregtechceu/gtceu/client/renderer/machine/ChargerRenderer.java [hunk 3]
```diff
@@ -56,24 +56,26 @@ public void renderMachine(List<BakedQuad> quads, MachineDefinition definition, @
...
-                    bakedFaces.add(FaceQuad.bakeFace(modelFacing, ModelFactory.getBlockSprite(CHARGER_FINISHED),
+                    bakedFaces.add(StaticFaceBakery.bakeFace(modelFacing, ModelFactory.getBlockSprite(CHARGER_FINISHED),
                             modelState, -1, 0, true, true));
                     if (ConfigHolder.INSTANCE.client.machinesEmissiveTextures) {
                         bakedFaces.add(
-                                FaceQuad.bakeFace(modelFacing, ModelFactory.getBlockSprite(CHARGER_FINISHED_EMISSIVE),
-                                        modelState, -101, 15, true, false));
+                                StaticFaceBakery.bakeFace(modelFacing,
+                                        ModelFactory.getBlockSprite(CHARGER_FINISHED_EMISSIVE), modelState, -101, 15,
+                                        true, false));
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/client/renderer/machine/ChargerRenderer.java]: I can't add it as a suggestion, but please consider reformatting this as follows:

```java
                        bakedFaces.add(StaticFaceBakery.bakeFace(
                                modelFacing, ModelFactory.getBlockSprite(CHARGER_FINISHED_EMISSIVE), 
                                modelState, -101, 15, true, false
                        ));
```

File: src/main/java/com/gregtechceu/gtceu/client/renderer/machine/MaintenanceHatchPartRenderer.java [hunk 4]
```diff
@@ -39,8 +39,9 @@ public void renderMachine(List<BakedQuad> quads, MachineDefinition definition, @
         super.renderMachine(quads, definition, machine, frontFacing, side, rand, modelFacing, modelState);
         if (side == frontFacing && modelFacing != null && machine instanceof IMaintenanceMachine maintenanceHatch &&
                 maintenanceHatch.isTaped()) {
-            quads.add(
-                    FaceQuad.bakeFace(modelFacing, ModelFactory.getBlockSprite(MAINTENANCE_OVERLAY_TAPED), modelState));
+            quads.add(StaticFaceBakery.bakeFace(StaticFaceBakery.SLIGHTLY_OVER_BLOCK, modelFacing,
+                    ModelFactory.getBlockSprite(MAINTENANCE_OVERLAY_TAPED), modelState, -1, 0, true,
+                    true));
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/client/renderer/machine/MaintenanceHatchPartRenderer.java]:
```suggestion
            quads.add(StaticFaceBakery.bakeFace(
                    StaticFaceBakery.SLIGHTLY_OVER_BLOCK, modelFacing,
                    ModelFactory.getBlockSprite(MAINTENANCE_OVERLAY_TAPED), modelState, -1, 0, true, true
            ));
```

File: src/main/java/com/gregtechceu/gtceu/client/renderer/machine/OverlayTieredMachineRenderer.java [hunk 5]
```diff
@@ -38,6 +42,25 @@ public void renderMachine(List<BakedQuad> quads, MachineDefinition definition, @
...
+    }
+
+    @Override
+    @OnlyIn(Dist.CLIENT)
+    public BakedModel getRotatedModel(Direction frontFacing) {
+        return blockModels.computeIfAbsent(frontFacing, facing -> getModel().bake(
+                ModelFactory.getModeBaker(),
+                new SpriteOverrider(override),
+                ModelFactory.getRotation(facing),
+                modelLocation));
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/client/renderer/machine/OverlayTieredMachineRenderer.java:60]:
```suggestion
        return blockModels.computeIfAbsent(frontFacing, facing -> getModel().bake(
                ModelFactory.getModeBaker(),
                new SpriteOverrider(override),
                ModelFactory.getRotation(facing),
                modelLocation
        ));
```

File: src/main/java/com/gregtechceu/gtceu/client/renderer/machine/PumpHatchPartRenderer.java [hunk 6]
```diff
@@ -43,9 +43,10 @@ public List<BakedQuad> renderModel(BlockAndTintGetter level, BlockPos pos, Block
                                        RandomSource rand) {
         if (state.getBlock() instanceof MetaMachineBlock machineBlock && side == machineBlock.getFrontFacing(state)) {
             var quads = new ArrayList<>(super.renderModel(level, pos, state, side, rand));
-            quads.add(FaceQuad.bakeFace(side, ModelFactory.getBlockSprite(PIPE_OUT)));
-            quads.add(FaceQuad.bakeFace(side, ModelFactory.getBlockSprite(FLUID_HATCH), BlockModelRotation.X0_Y0, -101,
-                    15));
+            quads.add(StaticFaceBakery.bakeFace(side, ModelFactory.getBlockSprite(PIPE_OUT)));
+            quads.add(
+                    StaticFaceBakery.bakeFace(side, ModelFactory.getBlockSprite(FLUID_HATCH), BlockModelRotation.X0_Y0,
+                            -101, 15));
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/client/renderer/machine/PumpHatchPartRenderer.java]:
```suggestion
            quads.add(StaticFaceBakery.bakeFace(
                    side, ModelFactory.getBlockSprite(FLUID_HATCH), 
                    BlockModelRotation.X0_Y0, -101, 15
            ));
```

File: src/main/java/com/gregtechceu/gtceu/client/renderer/machine/SimpleGeneratorMachineRenderer.java [hunk 7]
```diff
@@ -33,8 +33,9 @@ public void renderMachine(List<BakedQuad> quads, MachineDefinition definition, @
                               ModelState modelState) {
         super.renderMachine(quads, definition, machine, frontFacing, side, rand, modelFacing, modelState);
         if (side == frontFacing && modelFacing != null) {
-            quads.add(FaceQuad.bakeFace(modelFacing, ModelFactory.getBlockSprite(TransformerRenderer.ENERGY_OUT),
-                    modelState, 2));
+            quads.add(
+                    StaticFaceBakery.bakeFace(modelFacing, ModelFactory.getBlockSprite(TransformerRenderer.ENERGY_OUT),
+                            modelState, 2));
```
Comment (mikerooni) [inline src/main/java/com/gregtechceu/gtceu/client/renderer/machine/SimpleGeneratorMachineRenderer.java]:
```suggestion
            quads.add(StaticFaceBakery.bakeFace(
                    modelFacing, ModelFactory.getBlockSprite(TransformerRenderer.ENERGY_OUT),
                    modelState, 2
            ));
```

**Review by mikerooni — COMMENTED** [review]
Code looks good to me.

It seems like the formatting got messed up in a lot of places here. I'd suspect spotless automatically breaking lines at a certain length, but not 100% sure.

I've added formatting suggestions in the places where it negatively affects readability.

**Review by mikerooni — APPROVED** [review]
lgtm
