### PR TITLE
Fix facades coloring grass etc. with the underlying block's color

### LINKED ISSUE #2127: Facades taking on the color of pipes
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.4.4

### Minecraft Version

1.20.1

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

Monifactory

### Expected Behavior

Attached facade shows the grass texture with normal grass colors

### Actual Behavior

Attached facade shows the grass texture with colors influenced by the underlying pipe (bronze fluid/tin item)
image

### Steps to Reproduce

1) Place item/fluid pipe
2) Create grass facade using the 3 iron plate to block recipe

|Iron Plate|X|Iron Plate|
|----|----|----|
|X|Block|X|
|Iron Plate|X|X|

3) Place grass facade on top of pipe

### Additional Information

_No response_

### LINKED ISSUE #3058: Frames don't look correct when placed over pipes and cables
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.6.4

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

I have checked with the mod installed alone, on the GregTech CEu Modern Community Pack, and on my personal modpacks.

### Expected Behavior

When frames are placed over cables or pipes their texture should remain the same

### Actual Behavior

When frames are placed over cables or pipes their texture becomes weird, as if heavily saturated.

### Steps to Reproduce

Place a cable or any pipe and then place a frame over it (or vice-versa). The frames texture will look weird.

### Additional Information

This happens with any cable, fluid pipe or item pipe.

When pipes or cables are placed within frames that are part of a multiblock, the multiblock becomes invalid.

On my personal modpacks, frames don't act as ladders and cannot be climbed. While falling if I walk into a frame my movement stutters shortly.

### LINKED ISSUE #3356: Overlays of Steam Grinder and Steam Oven are not aligned
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.7.0-SNAPSHOT

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

JEI, EMI, Jade, Configuration

### Expected Behavior

Overlay should be close to the block's surface.

### Actual Behavior

Image
Image

The overlay seems to be a little bit "thicker" than other places.

### Steps to Reproduce

Place the controller blocks of Steam Grinder or Steam Oven

### Additional Information

_No response_

### LINKED ISSUE #3368: Facade don't have the proper icons and grass colour is wrong
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.0 snapshot

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

EMI

### Expected Behavior

Facades to have the proper icons and grass to match the biome grass

### Actual Behavior

left is grass facade, right is oak log facade
Image

grass matches the pipe underneath

Image

Image

### Steps to Reproduce

create facade
check the inventory icon

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by screret**
## What
title, did the same thing to frame boxes on pipes
also added More offset to the offsets
and fixed placing a facade moving ALL quads of the facaded block, e.g. every single stone block in the world would have a gap on the side
and made the item model nicer too

## Outcome
righter color, lefter gaps or something idk I think Im getting delirious
fixes #3368 
fixes #2127 
fixes #3356 
fixes #3058

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/client/model/TextureOverrideModel.java [hunk 1]
```diff
@@ -61,7 +61,7 @@ public static List<BakedQuad> retextureQuads(List<BakedQuad> quads,
             if (replacement != null) {
                 newQuads.add(GTQuadTransformers.setSprite(quad, replacement));
             } else {
-                newQuads.add(OVERLAY_OFFSET.process(quad));
+                newQuads.add(quad);
```
Comment (jurrejelle) [inline src/main/java/com/gregtechceu/gtceu/client/model/TextureOverrideModel.java:64]: We don't add the overlay offset here because we say that's up to the caller of retextureQuads now?

File: gradle/forge.versions.toml [hunk 2]
```diff
@@ -1,5 +1,5 @@
 [versions]
-ldlib = "1.0.40.a"
+ldlib = "1.0.40.b"
```
Comment (jurrejelle) [inline gradle/forge.versions.toml:2]: Why the version bump?

**Review by jurrejelle — COMMENTED** [review]
I have a few questions, apart from that LGTM, but we should keep in mind this will probably also cause more changes needed in CF?

File: gradle/forge.versions.toml (hunk 2 above)
Comment (screret) [reply gradle/forge.versions.toml:2]: It just fixes a crash

File: src/main/java/com/gregtechceu/gtceu/client/model/TextureOverrideModel.java (hunk 1 above)
Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/client/model/TextureOverrideModel.java:64]: Yes. And because it added gaps to everything.

**Review by jurrejelle — APPROVED** [review]
ok LGTM, but prob want another person reviewing this bcs 90% of it is magic to me xd

**Review by jurrejelle — APPROVED** [review]

**Review by YoungOnionMC — APPROVED** [review]
