### PR TITLE
Fix fluid cell dupe using AE2

### LINKED ISSUE #3599: [Bug] Fluid Cell Duplication Bug Using AE2 Crafting Terminal
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.2

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Playing on GregTech CEu Modern Community Pack. The interaction is between GregTech and Applied Energistics 2.

### Expected Behavior

Placing a filled fluid cell into the crafting grid should allow you to empty its contents entirely by "crafting" an empty one.

### Actual Behavior

When attempting to empty a fluid cell in the crafting grid inside of an AE2 terminal, it duplicates the cell whilst emptying only 2 buckets of the fluid in the original cell. This behaviour exists on all of the cells in the mod besides the standard 1 bucket cell and universal cell. It also occurs regardless of the fluid present in the cell.

Image

Image

### Steps to Reproduce

1. Fill a fluid cell besides the standard 1 bucket cell with any fluid.
2. Place it in an AE2 crafting terminal.
3. Attempt to "empty" the cell using the grid.

### Additional Information

_No response_

### LINKED ISSUE #3689: Cell duplication with Sophisticated Backpacks
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.1.4

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

sophisticated backpacks 3.23.23.1289 (latest at time of writing)
sophisticated core 1.2.80.1073 (latest at time of writing)

### Expected Behavior

Crafting a filled cell in a backpack's crafting grid should give you the empty cell back

### Actual Behavior

Crafting a filled cell in a backpack's crafting grid gives you 17 empty cells back

### Steps to Reproduce

https://github.com/user-attachments/assets/b5b1255c-c13d-451a-9831-0c04607550e3

### Additional Information

Only occurs with the backpack's crafting grid. Works fine in normal crafting tables. Also only happens with the cell is full? a partial cell doesn't have this dupe

https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/1570

### PR DESCRIPTION
**Pull request by TarLaboratories**
## What
Fixes duplication of cells by using the recipe that was intended to empty the cell in an AE2 crafting terminal (or sophisticated backpacks crafting upgrade)

## Implementation Details
I kinda just removed the crafting item remainder (well it's better than being able to dupe the cells)

## Outcome
Fixes #3689
Fixes #3599

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/common/item/ItemFluidContainer.java [hunk 1]
```diff
@@ -15,7 +15,7 @@ public ItemStack getRecipeRemained(ItemStack itemStack) {
             var drained = handler.drain(FluidType.BUCKET_VOLUME, FluidAction.SIMULATE);
             if (drained.getAmount() != FluidType.BUCKET_VOLUME) return ItemStack.EMPTY;
             handler.drain(FluidType.BUCKET_VOLUME, FluidAction.EXECUTE);
-            return handler.getContainer();
+            return ItemStack.EMPTY;
```
Comment (serenibyss) [inline src/main/java/com/gregtechceu/gtceu/common/item/ItemFluidContainer.java:18]: This now voids the cell in cases where the cell is used as a recipe input (for instance, crafting treated wood). Is there some way this can have awareness of what recipe this is running to know whether it is a cell clearing recipe vs a fluid input crafting recipe?

Comment (TarLaboratories) [reply src/main/java/com/gregtechceu/gtceu/common/item/ItemFluidContainer.java:18]: There is not unfortunately, fixing that would probably require a mixin into minecraft's crafting logic, not to mention issues with mods that add custom crafting tables

**Review by jurrejelle — APPROVED** [review]
