### PR TITLE
Fix scythe not breaking items in an AOE

### LINKED ISSUE #3970: Scythe AoE doesn't work.
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

v7.2.0

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Multiplayer - Dedicated Server

### Cross-Mod Interaction

Yes

### Other Installed Mods

TerraFirmaGreg v0.10.16

### Expected Behavior

A scythe should break in a 3x3/5x5 area.

### Actual Behavior

A scythe only breaks a single block.

### Steps to Reproduce

1) Get a scythe
2) Break a planted crop

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Ujhik**
## What
- Fixes #3970
- Corrects AoE block breaking behavior for the scythe
- Includes a small cleanup/refactor of getHarvestableBlocks to simplify logic and remove unused checks

## Implementation Details
The cleanup commit does not change tool behavior by itself, it only removes dead or redundant logic.

All changes were tested with multiple GregTech AoE tools, and everything behaved correctly in my tests, but a review is recommended.

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/item/tool/GTToolType.java [hunk 1]
```diff
@@ -125,7 +125,6 @@ public class GTToolType {
                     .aoe(2, 2, 2)
                     .behaviors(AOEConfigUIBehavior.INSTANCE, HoeGroundBehavior.INSTANCE, HarvestCropsBehavior.INSTANCE)
                     .canApplyEnchantment(EnchantmentCategory.DIGGER))
-            .constructor(GTHoeItem::new)
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/item/tool/GTToolType.java:128]: don't remove this, some mods (and sometimes vanilla) still check `instanceof HoeItem` for hoes etc.
make the spade an actual shovel item too while you're at it

**Review by screret — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/api/item/tool/GTToolType.java (hunk 1 above)
Comment (Ujhik) [reply src/main/java/com/gregtechceu/gtceu/api/item/tool/GTToolType.java:128]: Done

**Review by Spicierspace153 — APPROVED** [review]
