### PR TITLE
Fix cover behavior on busses and hatches

### LINKED ISSUE #3253: Can't put cover on the front of bus/hatch
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

1.7.0-SNAPSHOT+20250622-115911-5af8768

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

No

### Other Installed Mods

None

### Expected Behavior

Cover should be able to be placed on the front of bus/hatch

### Actual Behavior

Cover can be placed on any side of the bus/hatch except the front

### Steps to Reproduce

1) Use any multiblock with an bus/hatch
2) Try to place a cover on the front of the bus/hatch
3) Doesn't work

### Additional Information

I suppose it comes from the change #2830

### PR DESCRIPTION
**Pull request by jurrejelle**
## What
Allows covers on the front of busses/hatches.

## Outcome
Fixes https://github.com/GregTechCEu/GregTech-Modern/issues/3253

## Additional Information
I edited all input/output hatches (1x-4x-9x), input/output busses, input/output dual hatches. Any others I might have forgotten?

### CODE REVIEW

**Comment by screret** [comment]
cool lin- oh nvm there it goes.

**Comment by screret** [comment]
sbopbpless

File: src/main/java/com/gregtechceu/gtceu/api/registry/registrate/MachineBuilder.java [hunk 1]
```diff
@@ -151,6 +151,9 @@ public class MachineBuilder<DEFINITION extends MachineDefinition> extends Builde
     @Setter
     private boolean regressWhenWaiting = true;
 
+    @Getter
```
Comment (omergunr100) [inline src/main/java/com/gregtechceu/gtceu/api/registry/registrate/MachineBuilder.java]: `@Getter` isn't necessary

File: src/main/java/com/gregtechceu/gtceu/api/registry/registrate/MachineBuilder.java [hunk 2]
```diff
@@ -314,6 +317,11 @@ public MachineBuilder<DEFINITION> addOutputLimit(RecipeCapability<?> capability,
         return this;
     }
 
+    public MachineBuilder<DEFINITION> allowCoverOnFront(boolean allowCoverOnFront) {
+        this.allowCoverOnFront = allowCoverOnFront;
+        return this;
+    }
```
Comment (omergunr100) [inline src/main/java/com/gregtechceu/gtceu/api/registry/registrate/MachineBuilder.java]: this is covered by the `@Setter`

**Review by omergunr100 — CHANGES_REQUESTED** [review]
you should also override the setter on the multi builder to make it return a multi builder instance and not a single builder instance

File: src/main/java/com/gregtechceu/gtceu/api/cover/CoverBehavior.java [hunk 3]
```diff
@@ -100,7 +100,9 @@ public void onChanged() {
     @MustBeInvokedByOverriders
     public boolean canAttach() {
         var machine = MetaMachine.getMachine(coverHolder.getLevel(), coverHolder.getPos());
-        return machine == null || !machine.hasFrontFacing() || coverHolder.getFrontFacing() != attachedSide ||
+        return machine == null ||
+                (machine.getDefinition().isAllowCoverOnFront() || !machine.hasFrontFacing() ||
+                        coverHolder.getFrontFacing() != attachedSide) ||
                 machine instanceof IMultiController;
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/cover/CoverBehavior.java]: remove this check and set it to true by default on multiblocks instead

**Review by screret — CHANGES_REQUESTED** [review]

File: src/main/java/com/gregtechceu/gtceu/api/cover/CoverBehavior.java (hunk 3 above)
Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/api/cover/CoverBehavior.java]: the instanceof, I mean

Comment (omergunr100) [inline src/main/java/com/gregtechceu/gtceu/api/cover/CoverBehavior.java]: remove the multi controller check and set `allowCoverOnFront` to true by default in the multi builder

**Review by omergunr100 — CHANGES_REQUESTED** [review]

**Review by omergunr100 — APPROVED** [review]

**Review by omergunr100 — APPROVED** [review]

**Review by screret — APPROVED** [review]
