### PR TITLE
Fix multiblock controller rotation overlay logic

### LINKED ISSUE #4098: Rotation overlay doesn't appear
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

Latest 1.20.1

### Minecraft Version

1.20.1 Forge

### Recipe Viewer Installed

None

### Environment

Singleplayer

### Cross-Mod Interaction

Yes

### Other Installed Mods

Dev env

### Expected Behavior

Image

### Actual Behavior

Image

### Steps to Reproduce

Join world, place LCR, hold wrench

### Additional Information

seems to be broken since 7.0.0?

Image
back then we didn't even have lines, which we gained since then ,so upgrade at least xd

### PR DESCRIPTION
**Pull request by jkieberking**
## What
This fixes #4098 and unifies the multiblock controller's rotation overlay behavior with the singleblock machine's overlay (when holding a wrench and not sneaking/sneaking)

The singleblock logic is [here](https://github.com/jkieberking/GregTech-Modern/blob/1.20.1/src/main/java/com/gregtechceu/gtceu/api/machine/SimpleTieredMachine.java#L456-L464)

## Outcome

**not sneaking**
EBF:
image

LCR:
image

Electrolyzer:
image

**sneaking**

EBF:
image

LCR
image

Electrolyzer:
image

### CODE REVIEW

**Review by YoungOnionMC — APPROVED** [review]

**Review by screret — COMMENTED** [review]
From your screenshots I think multiblock controllers are now missing the center rotation icon
You should do this change to `MetaMachine#isFacingValid`:
```patch
@@ -596,4 +596,4 @@
 
     public boolean isFacingValid(Direction facing) {
-        if (hasFrontFacing() && facing == getFrontFacing()) return false;
+        if (hasFrontFacing() && facing == getFrontFacing() && !allowExtendedFacing()) return false;
         var coverContainer = getCoverContainer();
```

File: src/main/java/com/gregtechceu/gtceu/api/machine/MetaMachine.java [hunk 1]
```diff
@@ -533,7 +533,7 @@ public boolean shouldRenderGrid(Player player, BlockPos pos, BlockState state, I
         }
 
         if (toolTypes.contains(GTToolType.WRENCH)) {
-            if (player.isShiftKeyDown()) {
+            if (!player.isShiftKeyDown()) {
                 if (isFacingValid(side)) {
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/machine/MetaMachine.java]: From your screenshots I think multiblock controllers are now missing the center rotation icon, this should fix that:
```suggestion
                if (isFacingValid(side) || (allowExtendedFacing() && hasFrontFacing() side == getFrontFacing()) {
```

**Review by screret — DISMISSED** [review]

**Review by jurrejelle — APPROVED** [review]

**Comment by jurrejelle** [comment]
There was a typo in the suggestion, could you pull + add the missing ) + apply spotless + push? then I'll merge :)

**Review by YoungOnionMC — APPROVED** [review]
