### PR TITLE
[1.21] Fix GT tool repair logic

### LINKED ISSUE #3439: Crafting grid tool repair gives wrong durability
### Checked for existing issues

- [x] I have checked for existing issues, and have found none.

### Tested latest version

- [x] I have checked that this occurs on the latest version.

### GregTech CEu Version

7.0.1

### Minecraft Version

1.21.1 NeoForge

### Recipe Viewer Installed

EMI

### Environment

Singleplayer

### Cross-Mod Interaction

Unsure

### Other Installed Mods

- AppleSkin [3\.0\.7\+mc1\.21] (appleskin\-neoforge\-mc1\.21\-3\.0\.7\.jar)
- Applied Energistics 2 [19\.2\.13] (appliedenergistics2\-19\.2\.13\.jar)
- Architectury [13\.0\.8] (architectury\-13\.0\.8\-neoforge\.jar)
- Bad Packets [0\.8\.2] (badpackets\-neo\-0\.8\.2\.jar)
- Balm [21\.0\.46] (balm\-neoforge\-1\.21\.1\-21\.0\.46\.jar)
- CodeChicken Lib [4\.6\.1\.524] (CodeChickenLib\-1\.21\.1\-4\.6\.1\.524\.jar)
- Configuration [3\.1\.0] (configuration\-neoforge\-1\.21\.1\-3\.1\.0\.jar)
- EMI [1\.1\.22\+1\.21\.1\+neoforge] (emi\-1\.1\.22\+1\.21\.1\+neoforge\.jar)
- EMI Loot [0\.7\.6\+1\.21\+neoforge] (emi\_loot\-0\.7\.6\+1\.21\+neoforge\.jar)
- EMI Ores [1\.2\+1\.21\.1\+neoforge] (emi\_ores\-1\.2\+1\.21\.1\+neoforge\.jar)
- EnderStorage [2\.13\.0\.191] (EnderStorage\-1\.21\.1\-2\.13\.0\.191\.jar)
- FTB Chunks [2101\.1\.9] (ftb\-chunks\-neoforge\-2101\.1\.9\.jar)
- FTB Library [2101\.1\.16] (ftb\-library\-neoforge\-2101\.1\.16\.jar)
- FTB Teams [2101\.1\.2] (ftb\-teams\-neoforge\-2101\.1\.2\.jar)
- Fzzy Config [0\.7\.0\+1\.21\+neoforge] (fzzy\_config\-0\.7\.0\+1\.21\+neoforge\.jar)
- GregTech [7\.0\.1] (gtceu\-1\.21\.1\-7\.0\.1\.jar)
- GuideME [21\.1\.13] (guideme\-21\.1\.13\.jar)
- Inventory Tweaks Refoxed [1\.21\.1\-1\.2\.0] (invtweaks\-1\.21\.1\-1\.2\.0\.jar)
- Journeymap [1\.21\.1\-6\.0\.0\-beta\.52] (journeymap\-neoforge\-1\.21\.1\-6\.0\.0\-beta\.52\.jar)
- Kotlin for Forge [4qCjWixP] (kotlinforforge\-5\.9\.0\-all\.jar)
- LowDragLib [1\.0\.35\.a] (ldlib\-neoforge\-1\.21\.1\-1\.0\.35\.a\.jar)
- Sophisticated Backpacks [3\.24\.18] (sophisticatedbackpacks\-1\.21\.1\-3\.24\.18\.1280\.jar)
- Sophisticated Core [1\.3\.55] (sophisticatedcore\-1\.21\.1\-1\.3\.55\.1037\.jar)
- Waystones [21\.1\.19] (waystones\-neoforge\-1\.21\.1\-21\.1\.19\.jar)
- wthit [12\.5\.4] (wthit\-neo\-12\.5\.4\.jar)

### Expected Behavior

Combining 2 GT tools in the crafting grid should work similarly to combining vanilla tools (I think it's the combined durability of both tools + a small percentage).

### Actual Behavior

The resulting tool either has less durability than the combined durability of both tools:

Image

Or it has way more than expected. The closer to 0 durability both tools have, the closer to full durability the resulting tool seems to have:

Image

### Steps to Reproduce

Try to combine 2 tools in the crafting grid to repair.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Caedis**
Fixes https://github.com/GregTechCEu/GregTech-Modern/issues/3439

## What
See https://github.com/GregTechCEu/GregTech-Modern/issues/3439

## Implementation Details
Previous logic was setting the new item's damage to an incorrect value

## Outcome
Fixed logic for repairing GT tools to mimic vanilla repair logic

## Additional Information
image
image

### CODE REVIEW

**Review by Ghostipedia — APPROVED** [review]

**Review by Spicierspace153 — APPROVED** [review]

**Comment by Ghostipedia** [comment]
I'll let @screret take a double-look at this as she works on 1.21 a bunch

File: src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java [hunk 1]
```diff
@@ -69,8 +69,9 @@ public RepairItemRecipeMixin(CraftingBookCategory category) {
             cancellable = true)
     public void gtceu$assemble(CraftingInput input, HolderLookup.Provider registries,
                                CallbackInfoReturnable<ItemStack> cir,
-                               @Local(ordinal = 0) ItemStack itemstack,
-                               @Local(ordinal = 3) int calculatedDamage) {
+                               @Local(name = "itemstack") ItemStack itemstack,
+                               @Local(name = "i") int maxItemDamage,
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: You shouldn't use named locals, they're very brittle

**Review by screret — CHANGES_REQUESTED** [review]
The fix itself looks correct, just a stability suggestion

File: src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java (hunk 1 above)
Comment (Caedis) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: How is it brittle? I would think the ordinals would be more brittle if a mod used ASM to inject additional local variables

Comment (Caedis) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: Speaking in general, not in this specific area

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: It's what the docs recommend using. Idk more than that

Comment (Caedis) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: Got a link? I am sure modern mixin practices are different than what I was used to in NH in 1.7.10

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: It's on the mixin extras github wiki page for the local annotation

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: Also, basically nobody uses ASM here because you have to use JS for it.

Comment (Ghostipedia) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: +1 ASM is very rarely use in modern, It's notably just Mixins and at that point they'll clash anyway.

I don't think I've spotted a single usage of ASM in the past 1-2 years of packdev  on modern either.

Comment (Caedis) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: Ahh, good to know
image

Comment (Caedis) [reply src/main/java/com/gregtechceu/gtceu/core/mixins/RepairItemRecipeMixin.java]: Pushed

**Review by screret — APPROVED** [review]
