### PR TITLE
Fix that kinetic stress output will never not stop

### LINKED ISSUE #1109: The KINETIC_OUTPUT_BOX will never stop even if the machine was broken down
### Checked for existing issues

- [X] I have checked for existing issues, and have found none.

### Tested latest version

- [X] I have checked that this occurs on the latest version.

### GregTech CEu Version

directly source code

### Recipe Viewer Installed

None

### Environment

directly source code

### Cross-Mod Interaction

Yes

### Other Installed Mods

directly source code

### Expected Behavior

The KINETIC_OUTPUT_BOX should stop output stress when the machine is paused or broken.

### Actual Behavior

It never stop output stress once it is started, even if the entire machine except it is destroyed.

### Steps to Reproduce

```javasript
GTCEuStartupEvents.registry('gtceu:recipe_type', event => {
    event.create('cocat_steam_turbine')
        .category('example')
        .setEUIO('out')
        .setMaxIOSize(0, 0, 1, 1)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSteamProgressBar(GuiTextures.DISPLAY_STEAM, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ARC)
        .setMaxTooltips(6)

})

GTCEuStartupEvents.registry("gtceu:machine", event => {
    const LargeTurbineMachine = Java.loadClass("com.gregtechceu.gtceu.common.machine.multiblock.generator.LargeTurbineMachine")
    event.create("cocat_steam_turbine", "multiblock", (holder, trie) => new LargeTurbineMachine(holder, trie), 4)
        .rotationState(RotationState.NON_Y_AXIS)
        .appearanceBlock(GTBlocks.CASING_STAINLESS_TURBINE)
        .recipeType("cocat_steam_turbine")
        .recipeModifier((machine, recipe) => LargeTurbineMachine.recipeModifier(machine, recipe))
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("CCCC", "CHHC", "CCCC")
            .aisle("CHHC", "RAAR", "CHHC")
            .aisle("CCCC", "CSHC", "CCCC")
            .where("S", Predicates.controller(Predicates.blocks(definition.get())))
            .where("A", Predicates.blocks('create:flywheel'))
            .where("H", Predicates.blocks('gtceu:stainless_steel_turbine_casing')
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.MUFFLER).setExactLimit(1))
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS))
                .or(Predicates.abilities(PartAbility.OUTPUT_KINETIC).setExactLimit(1)))
            .where("R", Predicates.abilities(PartAbility.OUTPUT_ENERGY).setExactLimit(1)
                .or(Predicates.abilities(PartAbility.ROTOR_HOLDER).setExactLimit(1)))
            .where("C", Predicates.blocks("gtceu:stainless_steel_turbine_casing"))
            .build())
        .workableCasingRenderer(
            "gtceu:block/casings/mechanic/machine_casing_turbine_stainless_steel",
            "gtceu:block/multiblock/generator/large_steam_turbine", false)
});

ServerEvents.recipes(event => {
    event.recipes.gtceu.cocat_steam_turbine('steam')
        .inputFluids(Fluid.of('gtceu:steam',640))
        .outputFluids(Fluid.of('gtceu:distilled_water',4))
        .outputStress(32768)
        .duration(10)
        .EUt(-32)
})
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by iamSmallY**
Fix #1109 
The `preWorking` and `postWorking` is not called when the machine paused or destroyed.

### CODE REVIEW

File: src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java [hunk 1]
```diff
@@ -327,12 +322,24 @@ public void setupRecipe(GTRecipe recipe) {
         }
     }
 
+    private void notifyRecipeStatusChanged(Status oldStatus, Status newStatus) {
+        if (lastRecipe == null) {
+            return;
+        }
+        if (oldStatus == Status.WORKING && newStatus != Status.WORKING) {
+            lastRecipe.postWorking(machine);
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java]: what if `newStatus == Status.WAITING`? then the machine will do recipe completed actions whilst it's just out of energy.

Comment (screret) [reply src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java]: other cases like this exist as well.

File: src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java [hunk 2]
```diff
@@ -327,12 +322,24 @@ public void setupRecipe(GTRecipe recipe) {
...
+        } else if (oldStatus != Status.WORKING && newStatus == Status.WORKING) {
+            lastRecipe.preWorking(machine);
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/machine/trait/RecipeLogic.java]: ditto

**Review by screret — CHANGES_REQUESTED** [review]

**Comment by iamSmallY** [comment]
I rechecked the code logic and found that I could make changes in KineticPartMachine to fix this bug without modifying RecipeLogic. But now there is a problem that the stress output cannot be stopped when the controller is paused.

**Comment by screret** [comment]
you could add a callback for that maybe?

**Comment by iamSmallY** [comment]
I think now it will not have an excessive impact on the existing code logic.

File: src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/part/KineticPartMachine.java [hunk 3]
```diff
@@ -62,6 +70,47 @@ public void onRotated(Direction oldFacing, Direction newFacing) {
...
+        }
+        return super.onWorking(controller);
+    }
+
+    private void stopWhenControllerNotWorking() {
+        for (IMultiController controller : getControllers()) {
+            if (controller instanceof IWorkableMultiController workableMultiController) {
+                if (!workableMultiController.getRecipeLogic().isWorking()) {
+                    getKineticHolder().stopWorking();
+                    assert stopWorkingSub != null;
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/common/machine/multiblock/part/KineticPartMachine.java]: ...this will literally just crash if the subscription happens to be null, for example by the loop already succeeding.

**Review by screret — CHANGES_REQUESTED** [review]
I didn't say "do a second always-ticking thing to check it"
I said "add a callback for when the machine is paused in the recipe logic, and use it here to pause the hatch."

**Comment by iamSmallY** [comment]
I didn't know how to add the callback so I used a `TickableSubscription`. Do you think it is appropriate to call each part's setWorkingEnabled in `WorkableMultiblockMachine`?

**Comment by screret** [comment]
Well, look at what the onWorking/onWaiting etc. Methods do and apply that to this issue by adding an `onPaused`

File: src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IMultiPart.java [hunk 4]
```diff
@@ -91,6 +92,11 @@ default boolean onWaiting(IWorkableMultiController controller) {
         return true;
     }
 
+    /**
+     * Called in {@link WorkableMultiblockMachine#setWorkingEnabled(boolean)}
+     */
+    default boolean onPaused(IWorkableMultiController controller) { return true; }
```
Comment (screret) [inline src/main/java/com/gregtechceu/gtceu/api/machine/feature/multiblock/IMultiPart.java]: please format it correctly.

**Review by screret — CHANGES_REQUESTED** [review]

**Comment by iamSmallY** [comment]
Sorry, my IDE displays other method as one line.

**Review by screret — APPROVED** [review]
